### ISSUE TITLE
symfony-installer does not work well

### ISSUE THREAD

**Issue by paulywebster** [symfony/symfony-installer#100]
Hello, i use a vagrant box linux and i try the symfony installer.

I catch this error :

[03:27 PM]-[vagrant@packer-virtualbox-iso]-[/var/www] B
B$sudo symfony new vladwithsymfony

 Downloading Symfony...
    4.92 MB/4.92 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

PHP Warning:  copy(/tmp/142254530754ca519b76c0e/Symfony/bin/doctrine-dbal): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 211
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/symfony:0
PHP   2. require() /usr/local/bin/symfony:10
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:33
PHP   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Symfony\Installer\NewCommand->extract() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:68
PHP   9. Distill\Distill->extractWithoutRootDirectory() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:272
PHP  10. Distill\Extractor\Util\Filesystem->rename() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Distill.php:207
PHP  11. Distill\Extractor\Util\Filesystem->copyThenRemove() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:255
PHP  12. copy() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:211

Warning: copy(/tmp/142254530754ca519b76c0e/Symfony/bin/doctrine-dbal): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 211

Call Stack:
    0.0001     221128   1. {main}() /usr/local/bin/symfony:0
    0.0012     370904   2. require('phar:///usr/local/bin/symfony/symfony') /usr/local/bin/symfony:10
    0.0261    2159888   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:33
    0.0295    2538976   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0296    2539848   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0297    2540272   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0298    2543720   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    7.0101    5197624   8. Symfony\Installer\NewCommand->extract() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:68
    7.0101    5198672   9. Distill\Distill->extractWithoutRootDirectory() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:272
    8.1647    5375784  10. Distill\Extractor\Util\Filesystem->rename() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Distill.php:207
  206.9289    5755512  11. Distill\Extractor\Util\Filesystem->copyThenRemove() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:255
  311.7105    5775448  12. copy() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:211

PHP Warning:  copy(/tmp/142254530754ca519b76c0e/Symfony/bin/doctrine.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 211
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/symfony:0
PHP   2. require() /usr/local/bin/symfony:10
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:33
PHP   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Symfony\Installer\NewCommand->extract() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:68
PHP   9. Distill\Distill->extractWithoutRootDirectory() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:272
PHP  10. Distill\Extractor\Util\Filesystem->rename() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Distill.php:207
PHP  11. Distill\Extractor\Util\Filesystem->copyThenRemove() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:255
PHP  12. copy() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:211

Warning: copy(/tmp/142254530754ca519b76c0e/Symfony/bin/doctrine.php): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 211

Call Stack:
    0.0001     221128   1. {main}() /usr/local/bin/symfony:0
    0.0012     370904   2. require('phar:///usr/local/bin/symfony/symfony') /usr/local/bin/symfony:10
    0.0261    2159888   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:33
    0.0295    2538976   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0296    2539848   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0297    2540272   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0298    2543720   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    7.0101    5197624   8. Symfony\Installer\NewCommand->extract() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:68
    7.0101    5198672   9. Distill\Distill->extractWithoutRootDirectory() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:272
    8.1647    5375784  10. Distill\Extractor\Util\Filesystem->rename() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Distill.php:207
  206.9289    5755512  11. Distill\Extractor\Util\Filesystem->copyThenRemove() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:255
  311.7111    5775496  12. copy() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:211

PHP Warning:  copy(/tmp/142254530754ca519b76c0e/Symfony/bin/doctrine): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 211
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/symfony:0
PHP   2. require() /usr/local/bin/symfony:10
PHP   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:33
PHP   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Symfony\Installer\NewCommand->extract() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:68
PHP   9. Distill\Distill->extractWithoutRootDirectory() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:272
PHP  10. Distill\Extractor\Util\Filesystem->rename() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Distill.php:207
PHP  11. Distill\Extractor\Util\Filesystem->copyThenRemove() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:255
PHP  12. copy() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:211

Warning: copy(/tmp/142254530754ca519b76c0e/Symfony/bin/doctrine): failed to open stream: No such file or directory in phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php on line 211

Call Stack:
    0.0001     221128   1. {main}() /usr/local/bin/symfony:0
    0.0012     370904   2. require('phar:///usr/local/bin/symfony/symfony') /usr/local/bin/symfony:10
    0.0261    2159888   3. Symfony\Component\Console\Application->run() phar:///usr/local/bin/symfony/symfony:33
    0.0295    2538976   4. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0296    2539848   5. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0297    2540272   6. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0298    2543720   7. Symfony\Installer\NewCommand->execute() phar:///usr/local/bin/symfony/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    7.0101    5197624   8. Symfony\Installer\NewCommand->extract() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:68
    7.0101    5198672   9. Distill\Distill->extractWithoutRootDirectory() phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php:272
    8.1647    5375784  10. Distill\Extractor\Util\Filesystem->rename() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Distill.php:207
  206.9289    5755512  11. Distill\Extractor\Util\Filesystem->copyThenRemove() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:255
  311.7125    5775488  12. copy() phar:///usr/local/bin/symfony/vendor/raulfraile/distill/src/Extractor/Util/Filesystem.php:211

  [RuntimeException]
  Symfony can't be installed because the downloaded package is corrupted
  or because the installer doesn't have enough permissions to uncompress and
  rename the package contents.
  To solve this issue, check the permissions of the $ %s directory and
  try installing Symfony again.

new directory [version]

Sorry for the bread ... :)

**Comment by Pierstoval** [comment]
Do you have the rights on both `/var/www` and `/tmp/` directories ?

**Comment by weaverryan** [comment]
I will need to try it, but in a recent training, all trainees tried using the installer inside the VM in a VirtualBox "shared directory" (e.g. basically a network directory to the host machine). All 4 attendees also got this error. It could totally be unrelated to this issue, but the situation sounds very similar.

@paulywebster were you running this command from within a directory that's shared with your host machine (e.g. is "/var/www" shared)? If so, can you try again in a directory on your VM that is *not* shared with your host machine.

Thanks!

**Comment by paulywebster** [comment]
The problems seems not coming from the symfony-installer but clearly from vagrant with a nfs shared directory because when i try a git clone : i got an other error like this :fatal: fsync error on ... Permission denied and i've got some others error with composer. I find an issues who related this https://github.com/GM-Alex/vagrant-winnfsd/issues/22. 

So like @weaverryan propose, i try the installer in an other directory not shared and all works good ! I try a composer command and it works !!! And when i try a git clone it works too !!

So for resolve the probleme i thought and i need to try:

Create two vagrant box : the first with an SMB shared directory wherein i execute my command , normaly it should work 
and a second box with the same shared directory in nfs ( i use this because the performance of a symfony project on vagrant is really bad  between 15 and 30 sec loading and more sometimes) read more here :http://www.smartrock.fr/blog/windows/serveur-web-vagrant-lent-sous-windows-notamment-avec-symfony-voici-la-vraie-solution/ 

i will say more after try this ! Cross the finger !

Thanks to @weaverryan for your boost !

@Pierstoval i used the command with sudo so maybe i'm wrong but i think have the rihgt like root !

ps : sorry for my ugly english

**Comment by javiereguiluz** [comment]
What should we do to solve this problem?

  * Detect (if possible) that NFS is used and display an error message explaining the situation.
  * Fix (if possible) the Finder component to work on NFS folders.
  * ...

**Comment by paulywebster** [comment]
The problem is not coming from Symfony but from file system in vagrant between nfs filesystem and windows. So i think you don't need to solve this problem.

I try the solution says in my last post and it works well ! Except command on DB, because the vagrant boxes works on different DB. But the command works, this is what matters.

I find other solutions for speed-up symfony in vagrant : http://jeremybarthe.com/2015/02/02/speed-up-vagrant-environment-symfony2/ , so 'll try this.

**Comment by kdidenko** [comment]
Same problem is with Oracle's Virtual Box shared directory under Ubntu 14.10 - I can't create new project. Same error, and seems the only solution is to create new project at another directory

**Comment by kdidenko** [comment]
If you are using a virtual box with the shared folder under the Windows based host, the solution is easy, - just download the Symfony and start a new project to the same shared folder from the host system (windows) but not from the hosted Ubuntu. Worked fine for me after hour of suffering with same errors. Except I had to download PHP and configure the PATH variable on Windows side.

**Comment by sr972** [comment]
This 'issue' has been closed 7 month ago and already told that it is not a symfony installer bug but a fs thing between host and vm share. It's just the settings and the mount params in VB or an old VB utility driver problem.
