### ISSUE TITLE
Windows 8 problem with assets

### ISSUE THREAD

**Issue by welja** [symfony/symfony-installer#101]
When i create a new project using the symfony-installer (0.5.0)

![knipsel](https://cloud.githubusercontent.com/assets/1868810/5985972/74aa071e-a8eb-11e4-9098-e10ba571bee3.PNG)

the installer creates broken folders in the \web\bundles folder. 
I gues its trying to create symlinks on windows...

![knipsel](https://cloud.githubusercontent.com/assets/1868810/5985924/83bea620-a8ea-11e4-83d2-c2f75c80450b.PNG)

( earlier i downloaded symfony via composer and is detected that i was on windows and copied the assets over, but i thought, let's follow the [best practices](http://symfony.com/doc/current/best_practices/creating-the-project.html), then nothing can go wrong :)  )
So back to composer for me!

**Comment by stof** [comment]
@javiereguiluz looks like the archive contains the symlinks created by assets:install. this is a bad idea for portability. Installing assets should be done locally instead, so that it installs then for the OS being used.

**Comment by weaverryan** [comment]
:+1: And I think this is actionable. I don't think we've run any commands on the new project at the end of install yet, but we simply would need to run an `app/console assets:install`to fix this. The symlinked assets don't even need to be removed from the archive (as running the above command will overwrite them).

**Comment by stof** [comment]
@weaverryan this depends whether windows is able to delete the Unix symlink or whether it breaks when trying to delete them

**Comment by tkausl** [comment]
The same with /bin/, i had to delete vendor and "composer install" to get them recreated

**Comment by xabbuh** [comment]
IIRC the Symlinks in will be gone soon.

@javiereguiluz Do you know when this will be reflected in the archives?

**Comment by Pyjou** [comment]
I have make a composer update to fix this bug.
My PC use Windows 8.1, can you try this command @welja ?

**Comment by welja** [comment]
@Pyjou I thought  it was a bug in the symfony-installer? I do not understand your comment.
If there is something i can do to test, please let me know.

I did try the latest symfony-installer (1.0.0) just a moment ago and the bug is still there.

**Comment by HighOnMikey** [comment]
Just so there's a visual representation of what this bug does:

[Default install on Windows](http://i.imgur.com/jk3j4KT.png)
[Default install on Ubuntu](http://i.imgur.com/LXZdyQa.png)

Anyway, anyone who feels compelled to fix this, open a command prompt at your project root:

````
# At your project root
cd web\bundles
del *
mklink /J acmedemo ..\..\src\Acme\DemoBundle\Resources\public
mklink /J framework ..\..\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Resources\public
mklink /J sensiodistribution ..\..\vendor\sensio\distribution-bundle\Sensio\Bundle\DistributionBundle\Resources\public
````

This just removes all of the symlinks and creates them using Windows directory junctions.

**Comment by Pierstoval** [comment]
Does a simple `app/console assets:install --symlink` should fix the problem in Windows?

**Comment by HighOnMikey** [comment]
> Does a simple php app/console assets:install --symlink should fix the problem in Windows?

Yes and no. It fails to create symlinks/directory junctions so it simply copies the assets instead. If you *really* want symlinks you have to manually create them.

**Comment by Pierstoval** [comment]
It's strange because I used Windows 8 all last year to work with SF2 , and the symlinks were created without problem with this command. At home I have Windows 7 and the symlinks are also created.
This would mean that the installer should not embed any system-relative component, so get rid of the assets, and execute the command right after installing Symfony (manually or automatically)

**Comment by dhazelett** [comment]
Just wanted to chime in and report for Windows 7 as well. Both `web/bundles/` and `bin/{doctrine,security-checker}`.

The fix w/o `--symlink` option, works fine.

FWIW:

```
$ composer run-script post-install-cmd
Updating the "app/config/parameters.yml" file
Clearing the cache for the dev environment with debug true
Trying to install assets as symbolic links.
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
It looks like your system doesn't support relative symbolic links, so the assets were installed by using absolute symbolic links.
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution
It looks like your system doesn't support relative symbolic links, so the assets were installed by using absolute symbolic links.
```

**Comment by HighOnMikey** [comment]
To elaborate on what @dhazelett provided: Absolute symlinks are created using `composer run-script post-install-cmd` if Windows UAC is disabled or if you open a command prompt as an Administrator.

**Comment by KatharinaSt** [comment]
@HighOnMikey 
Thanks a lot! Your workaround works perfectly in the meantime!

**Comment by javiereguiluz** [comment]
Closing this 3-year old issue because of the lack of activity and because Symfony Flex has made the Symfony Installer obsolete, so there's no need to fix this. Thanks!
