### ISSUE TITLE
[DX] version command for new comers

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-installer#106]
Hi,

As the [symfony/installer] (http://symfony.com/doc/current/book/installation.html#installing-the-symfony-installer) is now the primary way to install a Symfony application, I propose for new comers this kind of command which can be great (if not knowing actual versions and their purpose).

Todo: add in the endpoint http://symfony.com/versions.json a description attached to each versions

I can PR my actual code if needed.

![symfony_versions](https://cloud.githubusercontent.com/assets/1358361/6308822/d24a1294-b947-11e4-852e-26db67714744.jpg)

![symfony_versions_install](https://cloud.githubusercontent.com/assets/1358361/6308821/d2460096-b947-11e4-896f-b8b9ac4661f7.jpg)

**Comment by Pierstoval** [comment]
I don't know if the `--install` feature is good, because there is a duplicate behavior with the `new` command.
 
The simple list is enough, IMO.

**Comment by fabpot** [comment]
I would do the opposite and add a flag to the existing command instead of adding a new one.

**Comment by 94noni** [comment]
Ok I will work on that option for the actual new command
What about the 'description' part in the versions api?
Thank you

**Comment by Pierstoval** [comment]
@fabpot You mean like the `--dump-sql` commands we have on some Doctrine ones ?
Plus, I'll probably change the table's look, duplicating the appearence of some versions is not the best for readability IMO :

```shell
$ symfony new --version
+----------------+------------------+--------+
| Symfony Branch | Resolved version |  Info  |
+----------------+------------------+--------+
| 2.3            | 2.3.25           | lts    |
| 2.5            | 2.5.10           |        |
| 2.6            | 2.6.4            | latest |
| 2.7            | 2.7.0-dev        | dev    |
+----------------+------------------+--------+
```

**Comment by fabpot** [comment]
@Pierstoval I think we don't need that much information about versions. A "newcomer" only need to know about the latest maintained version (2.6 here) and the LTS. 2.5 here is probably near its end of life, so that would be a non-sense to propose it. And giving the exat current version does not help in any way in choosing the right one. So, I'm not even sure it makes sense to use a table.

The choice is really just about LTS vs standard version.

**Comment by Pierstoval** [comment]
So showing only LTS and Latest sounds more relevant/useful to you ? I think that makes sense if it's for newcomers.

**Comment by 94noni** [comment]
Actually the code I've done is just a table output for the versions, and a question that run the new command if the option was passed with the choosed version
The idea behind is to allow a new comer to fastly detect the main latest version of the symfony framework

**Comment by fabpot** [comment]
@94noni My point of view and the whole goal of the symfony command is to not bother the user with the fine details. He just wants to install Symfony. Why would he choose to install 2.3, 2.5, or 2.6? He does not know. So, we install the latest stable version and soon he will be able to install the LTS. That makes sense as this is the only 2 versions that you really want to install when starting a new project.

**Comment by Pierstoval** [comment]
Using the LTS might not be for complete newcomers. Plus, if a user cares about LTS, won't he view it on the [download page](http://symfony.com/download) before and choose the version manually ?

**Comment by 94noni** [comment]
Understandable, of course showing this amount of versions is not the best for new comers
So no need actually only if we add a clear description here, with the option to dump majors versions

**Comment by javiereguiluz** [comment]
Reading your comments, I think that we don't need this feature:

If you are a newcomer:

  * You'll never use the LTS version for your Symfony projects.
  * Complicating the command help and documentation with a `--versions` option brings no benefit.
  * It's almost impossible that you clearly understand the differences between versions, so it's better to explain them on the website.

If you are an experienced Symfony developer:

  * You don't need this information because you know everything about versions.
  * You only need to be aware that `lts` version name is available ... but even that is not mandatory, because you know that `2.3.X` is LTS and you can use `2.3` in the installer.

**Comment by Pierstoval** [comment]
> It's almost impossible that you clearly understand the differences between versions, so it's better to explain them on the website.
 
If you're working in a company and expect to use the most stable Symfony version, I expect you know what is the difference between `latest` and `lts`.

**Comment by 94noni** [comment]
Ok fine so!
Closed as rhe 'lts' PR is already done :)

**Comment by javiereguiluz** [comment]
@Pierstoval I completely agree with you. Developers must know which are the differences. What I think is that the limited information about versions that we can provide in this command is not enough. It's better to read the information provided in symfony.com, see the roadmap of each version, etc.

**Comment by javiereguiluz** [comment]
@94noni thanks for understanding it. I know that is feels frustrating to work on some feature proposal and get rejected. I've experienced this situation first hand several times and it doesn't feel right.

However I'd like you to understand that the Symfony Installer is a very special software piece where we want to limit its features and options to almost zero. In fact, we consider it almost finished as it is.

**Comment by 94noni** [comment]
No worries, it was just a flat idea in mind :)
