### ISSUE TITLE
doctrine.php script missing from fresh install

### ISSUE THREAD

**Issue by minusf** [symfony/symfony-installer#107]
following the quick guide page on symfony.com, after creating a fresh project using
`php symfony.phar new project`, `vendor/doctrine/orm/bin` is missing and the
`bin/doctrine` symlinks are broken. after manually removing `vendor/` and
reinstalling using `php composer install`, the doctrine installation seems to be fine.
it seems that the symfony installer is doing something different in this case?

**Comment by xabbuh** [comment]
This is actually an issue of the tar archive provided on symfony.com. You can reproduce it yourself if you download [the archive for Symfony 2.6.4](http://symfony.com/download?v=Symfony_Standard_Vendors_2.6.4.tgz), for example, and extract it using the `tar` command.

Please note that this does not apply to the zip archive which is afaik used when you run the installer on system that doesn't support tar archives.

ping @fabpot @javiereguiluz

**Comment by minusf** [comment]
i see. hopefully the archive will get repaired by the powers to be :]

**Comment by javiereguiluz** [comment]
@xabbuh: these are the differences between the ZIP and the TGZ versions of Symfony

![symfony_zip_tgz](https://cloud.githubusercontent.com/assets/73419/6409555/a4e9973e-be65-11e4-8695-f2d81657f3e4.png)

What do you propose to do to fix these differences?
