### ISSUE TITLE
The download progressbar is broken on small console width

### ISSUE THREAD

**Issue by stof** [symfony/symfony-installer#109]
On small console widths, the download progressbar becomes longer than lines (the progress percentage wraps on next line). And this breaks the display of the progressbar: only the second line is replaced when overwriting the progressbar with the new display.

**Comment by xabbuh** [comment]
Is this related to symfony/symfony#13019?

**Comment by javiereguiluz** [comment]
I agree with @xabbuh: if there is an error in the progress bar, it's probably something related to the Console component, which is the one responsible for progress bars. But maybe I'm missing something.

**Comment by stof** [comment]
Yeah, this looks the same

**Comment by javiereguiluz** [comment]
I still think that this is clearly a Symfony issue, so let's close this issue and move the discussion to https://github.com/symfony/symfony/issues/13019. Thanks.
