### ISSUE TITLE
The new project contains a broken composer hook

### ISSUE THREAD

**Issue by stof** [symfony/symfony-installer#110]
The composer.json contains a ``post-root-package-install`` hook using ``SymfonyStandard\\Composer::hookRootPackageInstall``, but this class does not exist in the archive.

**Comment by stof** [comment]
OK, this is actually an issue in the symfony-standard itself. there is a hook removing these files on ``composer install`` but it does not remove the hook from the composer.json

**Comment by xabbuh** [comment]
I opened an issue on the SensioDistributionBundle repository which actually deletes the files in a script handler. So I close here in favor of sensiolabs/SensioDistributionBundle#215.
