### ISSUE TITLE
Download a specific version of the phar (homebrew)

### ISSUE THREAD

**Issue by dunglas** [symfony/symfony-installer#116]
Is it possible to download a specific version of generated PHARs? For instance symfony-1.0.0.phar?
My goal is to add the Symfony install to homebrew-php.

**Comment by romqin** [comment]
I don't know, but maybe we could do like @lyrixx's project: https://github.com/lyrixx/GithubComment/releases

**Comment by Pierstoval** [comment]
I don't know how homebrew works but can you link the package to the source and not use the phar file ? It may be better ?

**Comment by javiereguiluz** [comment]
@dunglas I'm afraid that it's not possible to download specific PHAR files. Fortunately, a script like the following should do the trick:

```bash
$ git clone https://github.com/symfony/symfony-installer.git
$ cd symfony-installer
$ git checkout tags/<INSTALLER VERSION NUMBER>
$ box build -v
```

Therefore, I'm closing this issue as *won't fix*. If you are not satisfied with this "solution", please reopen the issue to keep discussing about it. Thanks.

**Comment by stof** [comment]
@javiereguiluz What about attaching the phar to the Github releases ? this way, it would be possible to find the phar for any release. This is what Behat 3 does for instance.

**Comment by dunglas** [comment]
@stof does Behat 3 use a (public) tool to handle that?

**Comment by stof** [comment]
@dunglas The github releases are not created automatically. So for attaching the file, we just use the Github UI to upload the phar after it is generated.
However, I think the Github API allows to automate it.

**Comment by dunglas** [comment]
Yes it allows that.

I've started to design a tool to automate the release process of PHP application for API Platform. Currently I want it to:
- Download all required Composer dependencies (using `composer.lock`) for a given commit or tag of the project
- Create snapshot of the source with dependencies in ZIP, tarball or PHAR (box integration). This step is similar to what is required by the Symfony installer.
- Create SHA (or other security efficient algorithm) signature of the generated archive
- Upload the generated snapshot and the signature file in GitHub using the API

What do you think of using this tool for Symfony or Behat when it will be ready? I'll release it under the MIT license.

**Comment by Pierstoval** [comment]
If generated phars can be used as web-phars, I think that your tool will be absolutely awesome for any PHP app, @dunglas :D I'm :+1: for this :)

**Comment by josegonzalez** [comment]
Is there any reason why the release process can't include generated phar files? You already have a "latest" version, and it shouldn't be that much more difficult to just create phars for each release and at least link to them.
