### ISSUE TITLE
Windows users install

### ISSUE THREAD

**Issue by brunowego** [symfony/symfony-installer#117]
Simple way to install symfony-installer on Windows:

Get the PHP path install:
```bash
where php
```

Go to the PHP path, [download symfony-installer](http://symfony.com/installer), and run:
```bash
echo @php "%~dp0symfony.phar" %* > symfony.cmd
```

Run symfony-installer:
```bash
symfony
```

**Comment by Pierstoval** [comment]
Can't this information be written in the docs ?

**Comment by brunowego** [comment]
This is a alternative for local project install.

**Comment by Pierstoval** [comment]
Yep I know this alternative as I've been using it for some days, because my dev environment is under Windows, and my test/prod envs are under Linux, but this workaround to make symfony installer global has surely its place in the docs to explain users how to make it global even on windows :)

**Comment by brunowego** [comment]
I agree with you, that's what works for example with [phpunit](https://phpunit.de/manual/current/en/installation.html).

**Comment by Pierstoval** [comment]
Phpunit can also be installed globally using composer and putting the `bin` global composer directory into the $PATH

**Comment by brunowego** [comment]
Yes, will be nice too.
