### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#124]
Some people are asking us (via Twitter, email and symfony blog comments) to add support for using the installer behind a company proxy. I think it's a reasonable request and we should provide this feature if it's not too complicated.

Apparently, Composer provides proxy support just by [relying on some environment variables](https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy). Since we use a modern Guzzle version, where [proxy support is built-in and trivial to use](http://guzzle.readthedocs.org/en/latest/clients.html#proxy), do you think that would be enough to provide proxy support? Does this also apply to Windows users?

**Comment by raulfraile** [comment]
@javiereguiluz :+1: I also think that is an important feature as many people may need it. Even though the `env` variable would be enough, I suggest adding an optional argument to the command to make it easier to use, override the value of the `env` variable or create aliases. The command should also inform clearly that is using a proxy.

**Comment by blag001** [comment]
:+1: 
Need this Feature, for now I can't do anything of the new installer without the proxy support :/
For linux users, the classic way is to work with `http_proxy= | https_proxy= | ftp_proxy=` env variable.
(& for ubuntu user you can look for a network-manager proxy config)
But a `--proxy ` param like CURL will be fine too...
Thanks !

**Comment by javiereguiluz** [comment]
I'm going to work on this and I'l submit a PR soon.

**Comment by javiereguiluz** [comment]
There is a pull request (#132) ready to fix this issue. It would be great if real proxy server users could test it before merging it. To do so, just execute these commands in your system:

```bash
$ mkdir temp
$ cd temp/
$ git clone https://github.com/symfony/symfony-installer.git
$ cd symfony-installer/
$ git checkout -b test_proxy
$ git pull https://github.com/javiereguiluz/symfony-installer.git fix_124

$ ./symfony new my_project
```

**Comment by raulfraile** [comment]
@javiereguiluz it works fine using an anonymous proxy (I added a `var_dump()` to make sure it was setting the `proxy` setting in Guzzle):

```
$ export HTTP_PROXY=181.88.177.145:8080
$ php symfony new my_project9
```

![screen shot 2015-04-01 at 16 06 01](https://cloud.githubusercontent.com/assets/595160/6942627/230c20e0-d889-11e4-9cc9-19746442e97a.png)

It is much more slower, but it's normal as we are using a proxy.

More anonymous proxies: http://proxylist.hidemyass.com/

**Comment by raulfraile** [comment]
@javiereguiluz sorry, just found out that you had already tested it with a free proxy :)

**Comment by blag001** [comment]
I'll try this with my company proxy tomorrow ;)
Thanks for your work +

**Comment by rpayanm** [comment]
unsuccessfully :(
![Uploading Selection_050.png . . .]()

**Comment by javiereguiluz** [comment]
@rpayanm I'm really sorry but htere was an error in my installation instructions. I've updated them. Please note that AFTER `$ cd symfony-installer/` you must execute `$ composer install`:

```
$ mkdir temp
$ cd temp/
$ git clone https://github.com/symfony/symfony-installer.git
$ cd symfony-installer/
$ composer install
$ git checkout -b test_proxy
$ git pull https://github.com/javiereguiluz/symfony-installer.git fix_124

$ ./symfony new my_project
```

**Comment by rpayanm** [comment]
Perfect!
![selection_051](https://cloud.githubusercontent.com/assets/6087454/6964866/1d41c1fa-d91b-11e4-9cd2-d581005fd1e5.png)

**Comment by javiereguiluz** [comment]
@rpayanm great!

**Comment by blag001** [comment]
Nop, still don't want :-/
``` shell
blag@laptop:/tmp/temp/symfony-installer$ echo $http_proxy
http://10.2.10.102:8080
blag@laptop:/tmp/temp/symfony-installer$ ./symfony new my_project

 Downloading Symfony...
                                                                                                                                                      
  [GuzzleHttp\Exception\RequestException]                                                                                                             
  Error creating resource. [url] http://symfony.com/download?v=Symfony_Standard_Vendors_latest.tgz [type] 2 [message] fopen(http://symfony.com/downl  
  oad?v=Symfony_Standard_Vendors_latest.tgz): failed to open stream: Connection timed out [file] /tmp/temp/symfony-installer/vendor/guzzlehttp/guzzl  
  e/src/Adapter/StreamAdapter.php [line] 367                                                                                                          

new directory [version]
```
But it's ok with wget http://symfony.com/download?v=Symfony_Standard_Vendors_latest.tgz

**Comment by rpayanm** [comment]
@blag001 your proxy require authentication?
Your can paste here you proxy config in your /etc/wgetrc ?

**Comment by javiereguiluz** [comment]
@blag001 I have two quick questions for you:

  * Can you use Composer without problems in that same computer?
  * Do you have the proxy information defined as an environment variable? If you do `echo $HTTP_PROXY`, do you see your information? If not, do you see it in any other environment variable? (show all variables executing `export` in your console)

**Comment by blag001** [comment]
no identification,
my wgetrc : (without every ^#.+)
```
### Sample Wget initialization file .wgetrc
passive_ftp = on
```
no problem with composer if I export `http_proxy=` & `https_proxy=`
If you look back my quoted-console, I start with a echo $http_proxy ;-)
I try to define `HTTP_PROXY` too (upper-case), but :  
```
[GuzzleHttp\Exception\RequestException]                                      
  Error creating resource. [url] http://symfony.com/download?v=Symfony_Standa  
  rd_Vendors_latest.tgz [proxy] https://10.2.10.102:8080 [type] 2 [message] fo  
  pen(http://symfony.com/download?v=Symfony_Standard_Vendors_latest.tgz): fai  
  led to open stream: Unable to find the socket transport "http" - did you fo  
  rget to enable it when you configured PHP? [file] /tmp/temp/symfony-install  
  er/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php [line] 367
```
my export : 
```
declare -x HTTP_PROXY="http://10.2.10.102:8080"
#[...]
declare -x ftp_proxy="ftp://10.2.10.102:8080/"
declare -x http_proxy="http://10.2.10.102:8080/"
declare -x https_proxy="https://10.2.10.102:8080/"
declare -x no_proxy="localhost,127.0.0.0/8,::1"
```
Something strange : if I don’t set the upper-case http_proxy, the downloading wait a time out, but if I set the upper-case, then, I got the error above without waiting.

(end of the work for me, no more tests before tomorrow)

**Comment by blag001** [comment]
ok, my bad, my base /bin/php don't want to download anything.
If I use my /opt/lampp/bin/php (the one I usually use for symfony), it work fine ;)
```shell
 Downloading Symfony...

    4.91 MB/4.91 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony 2.6.6 was successfully installed. Now you can:

    * Change your current directory to /tmp/temp/symfony-installer/my_project

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php app/console server:run command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc

```

**Comment by javiereguiluz** [comment]
@blag001 I'm glad things seem to work now!  Seeing your export it was clear that the `HTTP_PROXY` and `http_proxy` environment variables were defined, so the code should work :)  Thanks for your patience testing this new feature. It will be merged soon.

**Comment by javiereguiluz** [comment]
Good news! A new installer version has just been released with proxy support. Get it executing `sudo symfony self-update` in your system.

**Comment by Pierstoval** [comment]
Great! :+1:

**Comment by meolivares06** [comment]
none of the options above works for me until i install php5-curl. 
After install it the order "symfony new blog" works fine with my env variables, in my case through gnome-proxy settings.

**Comment by RAM237** [comment]
**meolivares06**, thanks for the **php5-curl** suggestion, this has saved my life =)
