### ISSUE TITLE
Show progress during preparation

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-installer#126]
The longest part of the install process is the prepartion (at least on Windows). It's strange that this doesn't show any process, while the download does.

What about having a counter with some description?

```
 Preparing project...

     [1/10] Unpacking archive
```

I'm willing to create a PR, but I first want to know what people think about it.

**Comment by javiereguiluz** [comment]
@WouterJ that's surprising to me! The image that we use to promote the installer is a live recording of how does the installer work on my computer (and old Mac but with SSD):

![Symfony Installer in action](http://i.imgur.com/nyQH5VN.gif)

The recording is unedited and that's the time it takes to complete the "Preparing Project" task (less than 2 seconds).

How long does it take to complete on Windows? By the way, before adding progress information, I'd like to check if this is the result of a bad code on our side on the use of a bad technique for Windows and we should improve that part instead.

**Comment by WouterJ** [comment]
Interesting. I'll do some benchmarking today Windows to see if I can see which step is the problem.

**Comment by sstok** [comment]
Download is crazy fast. 

But the overall process takes 48 seconds on my machine!, 16GB ram and 4 cores.
One thing is that I'm running this on my F drive (HDD), the C is an SSD.

The extractor uses the Temp folder which is on a separate disk and then does a copy.
Extracting on the same disk and doing a move should be much faster.

**Comment by Pierstoval** [comment]
This behavior of copy/move is made by the FileSystem component. Unless we show logs to the user as proposed by @WouterJ to inform him of the process, I don't know how it can be optimized :confused:

**Comment by sstok** [comment]
Detect if Windows is used, and create a temp folder in the cwd instead of the temp folder?
But if your `/tmp` is on a separate mount point this will also be slow.

**Comment by javiereguiluz** [comment]
I've been chcking out the Distill library developed by @raulfraile that we use in the installer. This library first decides which package to download according to your system and then it actually extracts the contents.

The extraction is done sing the best method available, which depends on your system. Most of the times it uses a native OS command. Other times it uses a PHP extension and finally, sometimes it uses a extractor implemented in PHP.

If I've checked the code right, the problem may be [in these three lines](https://github.com/raulfraile/distill/blob/master/src/Method/Command/AbstractCommandMethod.php#L33-35). Basically, if you use Windows, you never use a command of your operating system. This looks quite drastic and I think we should do more advanced checks to see if some common commads such as 7zip is available on Windows.

**Comment by WouterJ** [comment]
| Method | Duration
| --- | ---
| `DownloadCommand::download` | 3 s
| `DownloadCommand::extract` | 90 s
| `DownloadCommand::cleanUp` | 0.05 s
| `DownloadCommand::updateParameters` | 0.01 s
| `DownloadCommand::updateComposerJson` | 0.01 s
| `DownloadCommand::createGitIgnore` | 0.01 s
| `DownloadCommand::checkSymfonyRequirements` | 0.08 s

The extraction process takes the most amount of time (90-100 s on my PC), so I decided to do some benchmarking in Distill:

| Method | Duration
| --- | ---
| `Distill::extract` | 90 s
| `Filesystem::rename` | 0.03 s

The Temp directory is on the same disk as the target location of the project.

Btw, funny thing: Tgz is taken from symfony.com, when I force it to use zip, the download takes 1 s more, but the extracting around 12 s less.

**Comment by javiereguiluz** [comment]
@WouterJ thanks for this detailed breakdown of what's happening under the hood. This seems to confirm my previous comment about not using binary commands on Windows. Let's ask @raulfraile which could be the best solution: tryng to use binary commands on Windows? Using other strategy for Windows?

**Comment by WouterJ** [comment]
Since I use Cygwin, I have some Unix commands in my windows terminal. So I did a bit of testing and I'm afraid things can't be optimized that much. The methods I had available and supported a format that was supported on symfony.com:

| Method | File format | Duration |
| --- | --- | --- |
| GnuTar (command) | tgz | - had a bug that didn't support paths starting with `C:\` |
| PharData (extension) | tgz | 112 s |
| Unzip (command) | zip | 234 s |
| Zip (extension) | zip | 65 s |

As you can see, the currently supported commands are by far not making things faster.

Btw, please also note https://github.com/raulfraile/distill/issues/6. Seems like @raulfraile wants to support Windows extract alternatives too.

**Comment by raulfraile** [comment]
I would like to support Windows binaries in Distill as @WouterJ pointed out, but I didn't have time nor a Windows machine. The reason of those three lines that @javiereguiluz linked to is that I haven't been able to test it on Windows. Once https://github.com/raulfraile/distill/issues/6 is working, it should make the process a lot faster

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because now that [Symfony Flex](https://github.com/symfony/flex) replaces the Symfony Installer, we won't add new features to the installer. Thanks for understanding it.
