### ISSUE TITLE
Files in bin directory are empty

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-installer#127]
After installation, the files in the `bin/` directory are empty. You have to execute `composer update` before you're able to use them.

**Comment by xabbuh** [comment]
Hm, I would have expected this to be solved with sensiolabs/SensioDistributionBundle#194.

**Comment by WouterJ** [comment]
The files are in there, but they are empty.

**Comment by xabbuh** [comment]
Are they really files or could it be that they are actually symlinks?

**Comment by WouterJ** [comment]
Hmm, could be (can't check right now)

**Comment by WouterJ** [comment]
For some reason, I can't reproduce this issue anymore. I'll close it and reopen if I am able to reproduce it

**Comment by xabbuh** [comment]
i assumed that your issue was related to the build of the archives for symfony.com. That should have been fixed recently. So maybe that's why you cannot reproduce it anymore.
