### ISSUE TITLE
Cannot install when parent directory is not writeable

### ISSUE THREAD

**Issue by gander** [symfony/symfony-installer#128]
You can not create a new installation of Symfony, in a directory that exists when the parent directory is not writeable:

`/path/no-writable/existing-project-dir/`

>   [RuntimeException]   
>   Symfony can't be installed because the downloaded package is corrupted or because the installer doesn't have enough permissions to uncompress and rename the package contents. To solve this issue, check the permissions of the /home/codio/workspace directory and try executing this command again:
>   symfony new .

**Comment by gander** [comment]
I misinterpreted error. Outdated.

**Comment by javiereguiluz** [comment]
@gander I'm glad that the error is gone. However, if you have any other trouble using the installer, please open a new issue. Thanks!
