### ISSUE TITLE
Why installer deletes project dir?

### ISSUE THREAD

**Issue by gander** [symfony/symfony-installer#130]
Too bad that the installer deletes the original folder. For example, in such a situation:

> codio:~/workspace$ ll
> drwxrwxr-x 2 codio codio 6 Mar 31 12:42 real 
> lrwxrwxrwx 1 codio codio 4 Mar 31 12:42 unreal -> real 
> 
> codio:~/workspace$ symfony new unreal 
> Downloading Symfony... 
> Preparing project... 
> 
> Symfony 2.6.5 was successfully installed.
> 
> codio@family-mixer:~/workspace$ ll
> drwxrwxr-x 2 codio codio   6 Mar 31 12:42 real 
> drwxr-xr-x 7 codio codio 132 Mar 31 12:43 unreal 

I need that there is a symbolic link, and I am getting an ordinary directory.

**Comment by Pierstoval** [comment]
Which version of the installer do you use ?

**Comment by gander** [comment]
>codio:~$ symfony --version 
>Symfony Installer version 1.0.2

**Comment by gander** [comment]
https://github.com/raulfraile/distill/blob/v0.9.8/src/Distill.php#L223-L224

**Comment by stof** [comment]
The workaround is to run ``symfony new real`` for now instead of using your symlink to give the path

**Comment by javiereguiluz** [comment]
Closing this 3-year old issue because of the lack of activity and because Symfony Flex has made the Symfony Installer obsolete, so there's no need to fix this. Thanks!
