### ISSUE TITLE
Add a warning message when the installer is not up-to-date.

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony-installer#136]
I was thinking about the releases process in the last issues, and I think that actually, the users will not often update their installer "knowingly".
 
I wanted to introduce a new proposal: an information/warning message when the installer is not up-to-date, similar to what Composer does:
![capture d ecran 2015-04-03 a 11 49 55](https://cloud.githubusercontent.com/assets/3369266/6980776/96264ffa-d9f7-11e4-8f0e-d624d03bb880.png)
 
But here we are facing one problem:
Once the installer will have maaaaany features, maybe there will not be new release for weeks/months.

Here is the tags list and their release date

```yml
2014-11-05: v0.0.1
2014-11-19: v0.0.2 # 14 days later
2014-11-20: v0.0.5 # 1 day later
2014-11-21: v0.1.0 # 1 day later
2014-11-26: v0.2.0 # 5 days later
2014-12-04: v0.3.0 # 8 days later
2014-12-08: v0.4.0 # 4 days later
2014-12-16: v0.5.0 # 8 days later
2015-02-27: v1.0.0 # 73 days later (more than 2 months)
2015-03-26: v1.0.1 # 27 days later
2015-04-03: v1.1.0 # 8 days later
```
 
As they're no regular update, we can't rely on the same Composer's behavior with the 30-days time comparison.
 
I was thinking on a solution by calling the Github API to check for all tags, and check a hard-coded version right inside the phar file, in any command, to compare directly the user's version with the latest release available, and then throw a warning whenever they're different, or when the user's one is inferior to the remote one.
Edit: FYI, we can see all tags on the API right here : https://api.github.com/repos/symfony/symfony-installer/tags .
 
Then it would allow the user to be warned whenever there's a new update, and possibly invoke some curiosity to him for he can go on Github and see the release note.
 
What do you think?

**Comment by javiereguiluz** [comment]
I thought about this feature and I discarded it for the same reasons that you pointed. In fact, the installer is "finished". We only fix reported bugs or add new features that are "mandatory" (such as the recent proxy server support).

In the future we'll only add features such as installing Symfony distributions (although it's not sure), caching of downloaded files (first we'll see if it's really needed) and file integrity verification through digital signatures (I'd like to add it but it looks like extremely complex to do it).

**Comment by xabbuh** [comment]
What do you think about doing the check only when we notice that the installation failed (when catching the exception). We could then display a message telling the user that the error might go away after an update (if one is available). Of course, this should then only be done for "unknown" exceptions (not the ones we treat explicitly).

**Comment by Pierstoval** [comment]
@xabbuh Nice idea, because the implementation might be done in some function in the abstract master command, because it might be good to use it in further implementations that might rely on other libraries and throw "unknown" exceptions.

**Comment by javiereguiluz** [comment]
That's definitely something we could do!

**Comment by WouterJ** [comment]
@javiereguiluz I think it's not a very good idea for the project's health and the love for your contributors to deny with "the installer is closed". As seen now, there is always room for improvement.

**Comment by Pierstoval** [comment]
I agree @WouterJ , many things will be discussed farther in time, and when Symfony3 will be released, there'll probably be new ideas coming up that will have to be handled by the installer.
 
Though I still think that there won't be updates every week or every month, so a warning about updates seems relevant to me, so if everyone agrees I might start working on this kind of feature :smiley:

**Comment by javiereguiluz** [comment]
Closing it because we're not going to implement this idea anytime soon. The reason is that, unlike Composer, we don't publish new versions of the Symfony installer frequently.

**Comment by sr972** [comment]
Was thinking about this feature some days. I still think, it's a necessary one. Especially because of the installer won't receive this much updates frequently. So there maybe some really needed updates, if there is a new version.

Wouldn't it just be easy enough to pack the current version of the installer into the JSON file for the packages and check against it, if you're using the installer? Couldn't be that hard to add something like "installerversion":"1.1.3" or :"1001003" and check against it on several commands. If the version in the JSON file is higher, just give a notification and thats it.

I for myself would still +1 this feature, even if or especially because there are not so much updates (that are published bysides the git version)

**Comment by weaverryan** [comment]
I also agree that this idea has merit.

Let's think about it a different way: what if there is a really nasty bug or even a security flaw in the installer? If that happened today, there'd be no way for us to add a "please update" flag to the existing, flawed installers.

**Comment by sr972** [comment]
This is exactly what i mean with my prev comment, Ryan!

**Comment by xabbuh** [comment]
@fabpot @javiereguiluz Can we expose the latest released version of the installer on http://symfony.com/versions.json too?

**Comment by javiereguiluz** [comment]
@xabbuh for Symfony versions we have some configuration options that quickly propagate the changes on symfony.com whenever a new Symfony version is released. Adding the Installer version would require us to also update that value by hand and that's very error prone because it's easy to forget to update it :(

**Comment by xabbuh** [comment]
What we could do then is to include the version of the installer in its code and query the GitHub API to check for updates. What do you think?
