### ISSUE TITLE
Installer generates write-protected files and folder on Windows

### ISSUE THREAD

**Issue by fweber-de** [symfony/symfony-installer#145]
Hi guys,

i tested the new Installer on Windows 7 for the first time and it produces write-protected files and folder at the target location. And it cant be removed too, after i remove the setting everything remains the same.

![](https://lh5.googleusercontent.com/-Bu1dyNckAH0/VS9713kZJtI/AAAAAAAAAmU/6Tt9EEsEh44/w529-h355-no/write-protection.png)

I can edit files in there though.
But i think this is not right nevertheless :smile:

**Comment by sstok** [comment]
Thats strange, did you run the command under a different user or something? I tried the last version but I don't have any write protected folder created (on Windows 7 Home).

**Comment by fweber-de** [comment]
@sstok i just checked again, in a powershell started as my user (not elevated).

In plain cmd.exe it works like a charm... :warning:

**Comment by javiereguiluz** [comment]
Closing this 3-year old issue because of the lack of activity and because Symfony Flex has made the Symfony Installer obsolete, so there's no need to fix this. Thanks!
