### ISSUE TITLE
Centos 5.5 installing does not work

### ISSUE THREAD

**Issue by CuAnnan** [symfony/symfony-installer#146]
All of the downloads get done.

 Preparing project...

PHP Fatal error:  Call to undefined function Symfony\Installer\posix_getpwuid() in phar:///usr/local/bin/symfony/src/Symfony/Installer/NewCommand.php on line 367

**Comment by dosten** [comment]
Seems that you are using and old version, the bug is fixed in #138. Can you run `symfony self-update`?

**Comment by CuAnnan** [comment]
I curled it down half an hour ago from the site, but I'll let you know

**Comment by CuAnnan** [comment]
PHP 5.5.23 (cli) (built: Mar 21 2015 22:04:59)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

thought this might be useful too.

**Comment by dosten** [comment]
Sorry, the fix introduced in #138 hasn't been released yet. @javiereguiluz it's possible to release v1.1.1?

**Comment by CuAnnan** [comment]
That's quite alright. I'm just glad it's not one of those "this is only effecting you" bugs.
I had an XKCD "WHAT DID YOU SEE" moment there.

**Comment by javiereguiluz** [comment]
@CuAnnan I'm really sorry that you suffered a bug that was already fixed by @dosten but not published. A new version of the installer has just been released. Get it as follows:

```bash
$ sudo symfony self-update
```

I'm closing this issue as fixed. If you still suffer any issue, please reopen it. Thanks!

**Comment by CuAnnan** [comment]
No apologies needed, these things happen. Thank you for the speedy resolution.
