### ISSUE TITLE
Error when running "symfony self-update"

### ISSUE THREAD

**Issue by ZCJ** [symfony/symfony-installer#147]
// updating Symfony Installer to 1.1.1 version

There was an error while updating the installer.
The previous Symfony Installer version has been restored.

**Comment by xabbuh** [comment]
@ZCJ Can you please run it again with the `-vvv` option and check if you get a more detailed error message?

**Comment by ZCJ** [comment]
@xabbuh I have tried it, but no further information .. screen shot attached

![screen shot 2015-04-21 at 12 01 39 pm](https://cloud.githubusercontent.com/assets/1475845/7247782/3bbcba1a-e81e-11e4-957a-350e38d7271b.png)

**Comment by javiereguiluz** [comment]
@ZCJ have you tried with `sudo symfony self-update`?

**Comment by ZCJ** [comment]
sudo did it ... my bad ...

**Comment by javiereguiluz** [comment]
@ZCJ I told you about `sudo` because this problem also caused a WTF!? moment to me. The problem is that the error message is not helpful at all. I'm going to prepare a pull request to improve it. For now, I'll close this issue as "fixed". Thanks.

**Comment by ZCJ** [comment]
Exactly.. A better error msg will help .. Thank you

**Comment by dsteplight** [comment]
Running "sudo symfony selfupdate" worked for me. It updated to the latest version which then allowed to successfully installed Symfony 3.2 .
