### ISSUE TITLE
Can't self-update the installer

### ISSUE THREAD

**Issue by Schizy** [symfony/symfony-installer#149]
Hello,

When i try to self-update the Symfony installer, i have the following error:

```
// updating Symfony Installer to 1.1.1 version

There was an error while updating the installer.
The previous Symfony Installer version has been restored.
```

**Comment by javiereguiluz** [comment]
@Schizy can you please try to update the installer with `sudo`?

```bash
$ sudo symfony self-update
```

This is probably the same problem as #147 and we're fixing it by improving the error message.

**Comment by Schizy** [comment]
It works! Thanks and sorry for created this issue for that

**Comment by javiereguiluz** [comment]
No need to worry. It's great to receive a lot of duplicated issues because it clearly shows that fixing this problem is both important and urgent. Cheers!
