### ISSUE TITLE
Error run symfony

### ISSUE THREAD

**Issue by juliosarango** [symfony/symfony-installer#150]
I run the following lines
$ sudo curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony
$ sudo chmod a+x /usr/local/bin/symfony 

I run symfony or symfony demo or symfony new_project in my terminal with fedora 19 and i have the error:

/usr/local/bin/symfony: línea 1: error sintáctico cerca del elemento inesperado `newline'
/usr/local/bin/symfony: línea 1: `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">'

Please help.

**Comment by javiereguiluz** [comment]
@juliosarango it seems that the download was corrupted or didn't work. The `symfony` binary file should be an executable PHAR file and it seems that in your case it's an HTML page.

If I open the `symfony` binaty with `vim` I get the following:

![symfony_binary](https://cloud.githubusercontent.com/assets/73419/7357123/e8a8a53c-ed2c-11e4-981d-6f7840789710.png)

What do you see if you do `vim /usr/local/bin/symfony`?

**Comment by juliosarango** [comment]
I followed the instructions on multiple computers getting the same error
message.



2015-04-27 15:30 GMT-05:00 Javier Eguiluz <notifications@github.com>:

**Comment by lyrixx** [comment]
If you are not confortable with vim, you can run the following command:
`strings /usr/local/bin/symfony  | head`

**Comment by juliosarango** [comment]
Hello.

Apparently the proxy and security policy blocked the correct download. From my
house all installed ok.
I can run the demo and any other installation.

Thanks for your attention.

2015-04-27 17:23 GMT-05:00 Grégoire Pineau <notifications@github.com>:

**Comment by javiereguiluz** [comment]
We supposedly support installing Symfony through a "normal proxy". Some people already use it without problems. In this function (https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/DownloadCommand.php#L159) you can see the code used to detect if we need to use a proxy. Basically we look for `HTTP_PROXY` and `http_proxy` environment variables.

But in your case, in addition to the proxy it looks like your company has some security policies blocking downloads. If that's true, I'm afraid we cannot solve this issue. Therefore, I'm closing this issue. But feel free to reopen it if you can provide us any other information to solve the issue. Thanks!
