### ISSUE TITLE
Installing symfony with new directory structure

### ISSUE THREAD

**Issue by colejarczyk** [symfony/symfony-installer#153]
Using composer, I can install Symfony with new directory structure by setting environment variable "SENSIOLABS_ENABLE_NEW_DIRECTORY_STRUCTURE=true"

How can I accomplish the same thing using this installer?

**Comment by xabbuh** [comment]
Hi @colejarczyk, this has been discussed before in #93 and it was decided to not support this directory structure in the installer for Symfony 2 applications. So I'm going to close here.
