### ISSUE TITLE
Add a directory argument to the demo command

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-installer#154]
Hi guys!

Small detail - I was just using the new `symfony demo` command (yay!) and I immediately wrote `symfony demo foo_bar_baz` - to make sure it didn't run over any existing directories. But, this argument doesn't exist.

I think it makes sense to have this argument (but not the version argument) - it's consistent with `symfony new`.

Thanks!

**Comment by lyrixx** [comment]
:+1:

**Comment by javiereguiluz** [comment]
:-1: I'm pretty much against adding this option ... but I'm in favor of not throwing an error when the user mistakenly adds the directory name.

The main reason is consistency, which is the same we achieved with the `AppBundle` recommendation. Thanks to `AppBundle` all tutorials, blog posts, docs and books use the same locations for things (no more `Acme`, `Foo`, `MyCompany`, etc. inconsistencies). Moreover, you can copy+paste any example and it works. You don't have to change the namespace of your entities or controllers.

The same goes for the Symfony Demo. In this case, given that the primary target are newcomers, this is specially important. Thanks to the no directory convention, there is no need to do anything before installing the demo and all the articles and docs can safely asume that the Symfony demo is installed in the `symfony_demo/` directory. This consistency simplifies everything.

**Comment by Pierstoval** [comment]
I don't think that the Symfony demo's primary target is newcomers. I can easily see trainings and learnings using the Symfony demo as a working base, so people like @weaverryan will certainly have to install the demo in trainings to use it.
And for instance, if you're a specialized Symfony teacher, and use the demo as a base for lessons, you'll certainly have *many* Symfony demos on your computer. For instance, I'd personally have a directory `teaching_sessions` in which I'll have one Symfony app for each session, so even if it always starts with the demo, I'll write code in them, and depending of the students/professionals I teach to, I would certainly have different code inside, especially if I train newcomers that can have a bright and fresh eye on the concepts, and propose awesome ideas in developing an app with Symfony.
 
I'm totally in favor of proposing a destination directory to the `symfony demo` command :+1:

**Comment by lyrixx** [comment]
@javiereguiluz I opened a PR ;)

**Comment by weaverryan** [comment]
@javiereguiluz I should have clarified that I'm quite ok with the directory being optional! @lyrixx PR (thanks by the way, that was fast!) keeps it optional.

To your point about consistency (which is a good one), I think beginners will copy and paste whatever command we give them. If we say `symfony demo` then `cd symfony_demo`, people will do exactly that. Only the curious/more advanced will ever know or care that the directory option exists.

**Comment by lyrixx** [comment]
I totally agree with @weaverryan. More over, the **current** demo command is able to [change the destination folder if `symfony_demo` exist](https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/DemoCommand.php#L43-L47).

it should be $i++ or $i=0, because right now, it starts at 2 ;)

**Comment by javiereguiluz** [comment]
@lyrixx the suffix appended automatically to the directory name starts with `2` on purpose. If a human being creates two folders with the same name, the first one will probably be called `symfony_demo` and the second one will be called `symfony_demo_2` instead of `symfony_demo_1`.

**Comment by stof** [comment]
@javiereguiluz btw, the currently logic for candidates is weird because the third candidate will be ``symfony_demo_2_3``, not ``symfony_demo_3``.
And btw, the fact that it changes the name automatically *already* means that the demo may be elsewhere than ``symfony_demo``. So allowing to control the name is fine IMO

**Comment by javiereguiluz** [comment]
> third candidate will be symfony_demo_2_3, not symfony_demo_3.

Then someone has changed this behavior. I've just executed `symfony demo` three times in a row and this is the result I got:

![symfony_demo](https://cloud.githubusercontent.com/assets/73419/7478235/9f60afae-f359-11e4-8b99-09cd06ba4e70.png)

**Comment by stof** [comment]
@javiereguiluz ah sorry, I looked at the code too fast
