### ISSUE TITLE
The selected version (2.5.11) cannot be installed because it does not exist.  

### ISSUE THREAD

**Issue by benstinton** [symfony/symfony-installer#158]
I've run the following on OSX:

symfony new project 2.5

 [RuntimeException]                                                            
  The selected version (2.5.11) cannot be installed because it does not exist.  
  Execute the following command to install the latest stable Symfony release:   
  /usr/local/bin/symfony new symfony

**Comment by 94noni** [comment]
Maybe we should already depreciate this version as it ends soon, no?

**Comment by xabbuh** [comment]
@fabpot Can you help us here? I can confirm that the archive for Symfony 2.5.11 at http://symfony.com/download?v=Symfony_Standard_Vendors_2.5.11.tgz cannot be downloaded.

**Comment by fabpot** [comment]
2.5.11 was a security release and as 2.5 is not maintained anymore, I don't release archives of Symfony SE. So, the installer should be fixed instead.

**Comment by xabbuh** [comment]
Alright, can we then update the script that publishes http://symfony.com/versions.json to not list not maintained Symfony versions as installable? Otherwise we would need to keep track of those versions in the installer which doesn't look right to me.

**Comment by fabpot** [comment]
@xabbuh doing it right now.

**Comment by fabpot** [comment]
fixed

**Comment by xabbuh** [comment]
@fabpot thanks

@benstinton You should now see a better error message like this:

```
  [RuntimeException]                                                                  
  The selected branch (2.5) does not exist, or is not maintained.                     
  To solve this issue, install Symfony with the latest stable release:                
  /home/christian/.bin/symfony new /home/christian/Symfony/symfony-installer/project 
```
