### ISSUE TITLE
Https to download installer doesn't work

### ISSUE THREAD

**Issue by WouterJ** [symfony/symfony-installer#160]
The current command to install the installer is:

    $ sudo curl -LsS https://symfony.com/installer -o /usr/bin/symfony

However, this does not work, as it redirects to `https://get.sensiolabs.org/symfony.phar`, which does not exist (sensiolabs.org does not yet support HTTPS).

/cc @fabpot @javiereguiluz

**Comment by xabbuh** [comment]
I can confirm this.

**Comment by fabpot** [comment]
Does it mean that nobody ever tested this? Is it something that we already recommend people to do? I'm confused here. ping @javiereguiluz

**Comment by javiereguiluz** [comment]
Regarding the server infrastructure, let's ping @lyrixx to notice hime about the SSL error with `get.sensiolabs.org` server.

Regarding the documentation error:

  * The README of this Symfony Installer repository only recommends to use HTTP (I've closed the PR that updated it to promote HTTPS).
  * The Installation chapter of the book still only recommends to use HTTP (there is a pending merge).
  * The symfony.com/download page is the only place where we recommend to use HTTPS but we're working to fix it.

**Comment by WouterJ** [comment]
@javiereguiluz I think it's better to fix the download page to use HTTP for now. It's confusing quite a lot of users...

**Comment by marshmn** [comment]
I just got hit by this... it's one of the first things a new user of Symfony may come across - before they even manage to get Symfony onto their machine - so I'd say it really needs fixing pretty fast...

**Comment by javiereguiluz** [comment]
You are right. That information is now stored in the symfony-marketing repo, so I've created the following PR: https://github.com/symfony/symfony-marketing/pull/261

**Comment by mhujer** [comment]
Workaround for getting the installer through https was adding this to my global `composer.json`:

     "symfony/symfony-installer": "*"

**Comment by xabbuh** [comment]
Closing here as the issue finally has been resolved.

**Comment by mhujer** [comment]
There is still `http` URL in the [docs](http://symfony.com/download).

**Comment by xabbuh** [comment]
@mhujer Thank you for noticing. I created symfony/symfony-docs#6035 to keep track of this.
