### ISSUE TITLE
Check write permission *before* downloading

### ISSUE THREAD

**Issue by ByScripts** [symfony/symfony-installer#175]
I think the installer should check for write permission **before** downloading (or at least reused the last downloaded one after permissions are fixed)

    symfony new my-project

    Downloading Symfony...

    4.95 MB/4.95 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

    [Symfony\Component\Filesystem\Exception\IOException]
    Failed to create "/var/www/.143660761855a0e482d53bd": mkdir(): Permission denied.

After that, if I fix the permissions and run `symfony new my-project` again, then Symfony is re-downloaded.

Although it's not a problem for me, it could be for those who have a slow connection.

**Comment by javiereguiluz** [comment]
@ByScripts thanks for this suggestion. I like it a lot because it's easy to do, it adds value and it improves the user experience. I'm trying to implement it in #176.
