### ISSUE TITLE
Check that the system is ready to execute the installer properly

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#179]
In https://github.com/symfony/symfony-installer/issues/151#issuecomment-124044930 @jamalsa reported that his system didn't execute the installer properly because of:
1. Phar extension is not enabled by default. You can enable this in php.ini (in Arch and Manjaro its located at /etc/php/php.ini) by remove leading semicolon in ;extension=phar.so.
2. /usr/local/bin/symfony is not in open_basedir. Add it in php.ini.

We should check for these and any other requirement and tell the user about them.

**Comment by sstok** [comment]
Just a big shot in the dark here, but would it be an idea to provide actual software packages like deb, rpm, exe (or msi) and whatever Mac uses (dmg?) and let these configure the PHP install the phar command in a system location.

It would actually solve the problem of distributing a signed package and still being able to check/prepare the env without having to download and run an (unsigned) script!

**Comment by Pierstoval** [comment]
We could also provide packages for Mac-Homebrew and Windows-Chocolatey (especially with the upcoming Windows 10, implementing a fork of Chocolatey).
 
For Composer, actually, the installer simply installs the phar file combined with a `composer.bat` in the `%PATH%` that will run the phar automatically. It's "just a workaround"...

**Comment by javiereguiluz** [comment]
At the very beginning, we thought about providing a software packages and a graphical installer, but we discarded it for several reasons:

  * The current PHAR-based installer weights just 189 KB. A software package (MSI, DMG) can weight up to several MB.
  * PHP/PHAR support is "universal". Using a software package would force us to create 6 different installers and we should drop support for systems which support PHP but not one of the given packages.

Besides, I don't see how creating packages could solve this issue. Right now we're struggling to sign one PHAR file. If we create 6 software packages, we must sign and maintain 6 installers.

Signing the installer would be great ... and one day we'll do it. But for now, you can check out this repository, carefully review its code and execute one command (`box build`) to build the installer safely.

**Comment by xabbuh** [comment]
Is it actually possible to perform this check from inside the phar at all if the extension is disabled? Would be very weird if that were possible.

**Comment by xabbuh** [comment]
Is it actually possible to perform this check from inside the phar at all if the extension is disabled? Would be very weird if that were possible.

**Comment by neuro-sys** [comment]
Changing the phar such that it has the contents of the following would be helpful for beginners in this case.
```php
if (class_exists('Phar')) {
Phar::mapPhar('default.phar');
require 'phar://' . __FILE__ . '/symfony';
} else {
    echo "Phar extension is not enabled by default. You can enable this in php.ini (in Arch and Manjaro its located at /etc/php/php.ini) by remove leading semicolon in ;extension=phar.so.\n";
}

```
Except this file is automatically generated by Box it seems, in which case the change should be done in Box upstream, or with a script that'll edit the generated file in symfony-installer.

**Comment by sstok** [comment]
@neuro-sys You can use the http://php.net/manual/en/function.php-ini-loaded-file.php function to get the location of the php.ini file :+1: but it's not always reliable (split out configuration files).

You would need to use http://php.net/manual/en/function.php-ini-scanned-files.php to for search for a potentially related files. But better is to just point to an url with more general information :)

**Comment by dbu** [comment]
I think simple checks like phar support in the bash script would really be good to ease the first encounter with symfony.

I just ran into another one: When a new project is created, it seems to require the dom extension, but that is not checked (and not added to the `require` section in composer.json). After the vendor install, i get a fatal error that `DOMDocument` is not found. I am not asking for help here - i know what to do - but to a new user it would be much better to run the requirements check before downloading everything and then fail with a stacktrace in the middle of cache:clear.

**Comment by Pierstoval** [comment]
I encountered the exact same issue some months ago with students in a school that didn't allow to update internal PHP config, they ended up with VMs, and I forgot to report it here, 👍 for reporting it @dbu

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because now that [Symfony Flex](https://github.com/symfony/flex) replaces the Symfony Installer, we won't add new features to the installer. Thanks for understanding it.
