### ISSUE TITLE
symfony new command causes fatal error with PHP 7.0.0RC2

### ISSUE THREAD

**Issue by michaelthieulin** [symfony/symfony-installer#181]
Hello,

I try the installer with PHP 7.0.0RC2.

When i execute the following command :
```
symfony new sfphp7
```

it fails with the following error and trace :
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to GuzzleHttp\Adapter\StreamAdapter::createResponseObject() must be of the type array, null given, called in phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php on line 67 and defined in phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php:71
Stack trace:
#0 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php(67): GuzzleHttp\Adapter\StreamAdapter->createResponseObject(Object(GuzzleHttp\Message\Request), NULL, Object(GuzzleHttp\Adapter\Transaction), Object(GuzzleHttp\Stream\Stream))
#1 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php(52): GuzzleHttp\Adapter\StreamAdapter->createResponse(Object(GuzzleHttp\Adapter\Transaction))
#2 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Client.php(193): GuzzleHttp\Adapter\StreamAdapter->send(Object(GuzzleHttp\Adapter\Transaction))
#3 phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src in phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/Adapter/StreamAdapter.php on line 71
```

Thanks

**Comment by stof** [comment]
this should probably be reported to Guzzle rather than here. This issue happens in Guzzle

**Comment by michaelthieulin** [comment]
Not sure because symfony installer depends on Guzzle 4.x (cf. https://github.com/symfony/symfony-installer/blob/master/composer.json#L17) which is not maintained anymore. The last version of Guzzle is 6.1.0 which seems to be php 7 compatible (honestly i didn't found this information anywhere but i saw several commits related with this).

**Comment by javiereguiluz** [comment]
I'm going to investigate this and make some tests with the latest Guzzle version. @michaelthieulin thanks for reporting this issue and for the info provided.

**Comment by stof** [comment]
we should try to upgrade to Guzzle 5 at least (Guzzle 6 would be harder as it is a complete rewrite of the library). It may require changing the way we report progress though.

The other issue with upgrading the guzzle to 6 is that we would have to bump the installer requirements to 5.5+, and I'm not sure whether it is OK. Note that guzzle 5 is still supported

**Comment by javiereguiluz** [comment]
Yes, Guzzle 6 is out of question because of the PHP 5.5+ requirement.

**Comment by javiereguiluz** [comment]
@michaelthieulin in #182 I've updated Guzzle to its version 5. It'd be great if you could test the changes in your PHP 7 installation. Thanks!

**Comment by michaelthieulin** [comment]
:+1:
