### ISSUE TITLE
Add an option to install symfony from the master/dev repository.

### ISSUE THREAD

**Issue by naroga** [symfony/symfony-installer#191]
Symfony 3.0 is scheduled to be released this month. I'm just starting a new project, which won't be completed until 2016. I'd like an option to install the master release (I know it's not stable, but it's not like it's going into production or anything) .

The only option I have right now is installing directly through composer, which creates a slightly different directory structure then the symfony installer.

**Comment by xabbuh** [comment]
You will be able to use the installer as soon as the first release candidate is published.

**Comment by stof** [comment]
Installing from composer does *not* create a different structure than the installer if you use the symfony-standard repo to bootstrap your project.

If you install ``symfony/symfony`` as the root, it of course creates a different directory structure, but this is not how Symfony is meant to be used: it is a dependency of the project, not the project itself.

@xabbuh even as soon the first beta is.

**Comment by naroga** [comment]
@xabbuh and @stof: I figured I'd be able to use it soon, but I see no reason why the installer wouldn't allow `master` or `dev-master` as a possible version, so I thought I'd suggest it here (even if a beta is near, in the future, the installer could allow me to install the master for 3.1).

@stof: I just tested, and you are correct. I don't know where I got that from. Still, I think it would be nice to allow the installer to install dev versions.

**Comment by stof** [comment]
@naroga the installer downloads a pre-built archive from the SensioLabs server. There is no such archive for branches, as it would require to rebuild it on each commit, which is not maintainable. This is why they are available only for releases (beta, RC or stable ones)

**Comment by naroga** [comment]
@stof, well, that's a perfectly reasonable explanation. I'll close the issue then. Thank you for your time.
