### ISSUE TITLE
Does the installer need to be run as root/with sudo?

### ISSUE THREAD

**Issue by sergiu-popa** [symfony/symfony-installer#192]
I started using the installer and everytime I create a new project I still need to set up permissions for logs and cache folders (http://symfony.com/doc/current/book/installation.html#book-installation-permissions). Does the installer try to chmod correctly these directories or it's not yet implemented?

Thank you.

**Comment by Pierstoval** [comment]
The chmod can be set up by the installer, but one should remember that permissions can also be set up with acl better than simple chmod

**Comment by javiereguiluz** [comment]
The installer doesn't set the permissions of the folders because it's "impossible" to do it right ofr every kind of operating system and configuration (Vagrant, etc.)

Our recommendation is to use the first method explained in the Symfony book:

```
1. Use the same user for the CLI and the web server

In development environments, it is a common practice to use the same UNIX user for the CLI
and the web server because it avoids any of these permissions issues when setting up new
projects. This can be done by editing your web server configuration (e.g. commonly httpd.conf
or apache2.conf for Apache) and setting its user to be the same as your CLI user (e.g. for
Apache, update the User and Group values).
```

This works perfectly and it's safe to do it in your local machine.

**Comment by xabbuh** [comment]
The same applies, by the way, when you use PHP's built-in web server as it is executed with the rights of the user starting it.

**Comment by sergiu-popa** [comment]
Thanks for the tip. I'll set up this today.
