### ISSUE TITLE
The new command needs to update the content-hash in the lock file

### ISSUE THREAD

**Issue by stof** [symfony/symfony-installer#195]
The composer.lock now contains 2 hashes:

- the old ``hash`` property which hashes the full composer.json file
- the new ``content-hash`` property, which hashes only the settings relevant to the resolution algorithm

New versions of composer will ignore the hash if the content-hash is there, avoiding to show a warning in case you change the composer.json in a non-meaningful way (changing the formatting, changing the suggest section, etc...).

As the installer updates the name in the composer.json and this name is taken into account by the content-hash, it needs to update the content-hash too, not only the hash.

**Comment by Pierstoval** [comment]
It would need to generate the hash based on the same script than Composer itself, wouldn't it create edge cases in the future?

**Comment by stof** [comment]
@Pierstoval we need to update it. The *way* we do it is still to be determined, to be future-proof. See my comment on the original implementation: https://github.com/symfony/symfony-installer/pull/173

for reference, he content hashing logic is at https://github.com/composer/composer/blob/master/src/Composer/Package/Locker.php#L394-L431
