### ISSUE TITLE
Does the installer support 2.8 and/or 3.0 already?

### ISSUE THREAD

**Issue by paquitodev** [symfony/symfony-installer#201]
I am asking if the Symfony installer already support Symfony 2.8 and/or 3.0 and which are the command line to install them if not I would like to know the right way to install them since I am starting a new project and I am planning to do with one of those versions due to early release date. Any advice on this?

**Comment by Pierstoval** [comment]
2.8 is supported as there is a beta release so you can do `symfony new my_project 2.8.0-beta1` without problems.
For 3.0 there's a PR waiting for discussion: #198

**Comment by javiereguiluz** [comment]
Closing it as fixed.
