### ISSUE TITLE
app/AppKernel.php is in the class loader file map, causing invalid bootstrap.php.cache file generation

### ISSUE THREAD

**Issue by pounard** [symfony/symfony-installer#213]
I did experience this trying to ugprade to Symfony 3.

Because I experienced dependency problems, I started by creating a fresh project to have a look over the composer.json file and set the right versions in my own project, so I did it.

I noticed that the newly generated composer.json contains this:

	"autoload" : {
		"psr-0" : {
			"" : "src/"
		},
		"files" : [
			"app/AppKernel.php"
		]
	},

The result is that **the *app/AppKernel.php* file is being loaded prior to the *bootstrap.php.cache* file** generation.

When the *Symfony\Component\ClassLoader\ClassCollectionLoader* is trying to generate the cache file, we can read this piece of code (line 99):

        if (in_array($class->getName(), $declared)) {
            continue;
        }

Most of the class chain required by the Kernel class (being used in *app/AppKernel.php*) is declared because already autoloaded.

Because those class are declared, they are being ignored and not dumped: on next run, **an incomplete bootstrap.php.cache file is loaded and generate PHP fatal errors due to missing interfaces**.

**Comment by pounard** [comment]
Once I removed the extra autoload file, and generated manually the file using the build script in the Resource/bin folder, I got another error, Console component is not properly loaded when running app/console because it relies only the bootstrap cache and it does not uses the composer autoload, maybe this is an upgrade problem ?

**Comment by stof** [comment]
@pounard SensioDistributionBundle 5.0 requires to load the autoloader separately from the bootstrap.php.cache file. Make sure your project contains the same changes than the SE.

anyway, this repo is the wrong place to ask for issues updating an existing project to Symfony 3, since you are not using the installer in such case

**Comment by xabbuh** [comment]
@pounard FYI, see sensiolabs/SensioDistributionBundle#242 and the upgrade instructions on https://github.com/symfony/symfony-standard/blob/2.8/UPGRADE-2.8.md

**Comment by pounard** [comment]
Yes, did find it out by myself, thank you very much.

**Comment by pounard** [comment]
This is not documented in the http://symfony.com/doc/current/cookbook/upgrade/major_version.html page, and I do think it's a very bad thing because a lot of people will start from there, hence the mess up. At least it pushed me to xdebug the installer and the bootstrap cache generator, so I will end up less ignorant tonight.

**Comment by xabbuh** [comment]
@pounard FYI, I opened an issue for this in the docs repository: symfony/symfony-docs#5941

**Comment by pounard** [comment]
Actually, I'm reopening this, for the exact reason I wrote in the original post, most interfaces that are mandatory are dropped from the bootstrap cache, and that's a potential performance regression.

**Comment by pounard** [comment]
@xabbuh Thank you very much.

**Comment by stof** [comment]
the change in https://github.com/symfony/symfony-standard/pull/897 should fix it. @pounard can you confirm it by applying this change in your project ?

**Comment by pounard** [comment]
@stof I experienced some problems for migration to 3.x because the console component was trying to load app/console (version 2.7, non regenerated) and failing because the autoloader was not being registered, I just manually patched it, fixed manually my tree to match 3.x and fixed my composer.json file an now that's OK, I don't have anymore problems, I guess symfony/symfony-standard#897 probably won't fix any crash since I don't have any.

But now, what is wrong, is that the bootstrap.php.cache has a few classes inside, but does not carry the class, interfa

**Comment by pounard** [comment]
@stof I experienced some problems for migration to 3.x because the console component was trying to load app/console (version 2.7, non regenerated) and failing because the autoloader was not being registered, I just manually patched it, fixed manually my tree to match 3.x and fixed my composer.json file an now that's OK, I don't have anymore problems, I guess symfony/symfony-standard#897 probably won't fix any crash since I don't have any.

But now, what is wrong, is that the bootstrap.php.cache has a few classes inside, but does not carry the class, interface nor traits chain of those classes, because in all cases (console or composer or build_bootstrap.php) those files are already preloaded by the AppKernel.php file loading.

**Comment by pounard** [comment]
@stof, this does fixes it, thanks.
