### ISSUE TITLE
run:server - Segfault on syntax error

### ISSUE THREAD

**Issue by Booteille** [symfony/symfony-installer#216]
Hi.

I just got a *Segmentation Fault* error while running the build-in *Symfony PHP server*.

It happened with the following code:

```php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $response = $this->render('')
    }
}
```

I ran again the server with *verbose* option and here is what server displayed:
```shell
                                                                                                                        
 [OK] Server running on http://127.0.0.1:8000                                                                           
                                                                                                                        

 // Quit the server with CONTROL-C.
  RUN  '/usr/bin/php7.0' '-S' '127.0.0.1:8000' '/home/booteille/PhpstormProjects/my_project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/config/router_dev.php'
  ERR  [Fri Dec  4 05:20:17 2015] 127.0.0.1:60062 [500]: /
  ERR  [Fri Dec  4 05:20:18 2015] 127.0.0.1:60063 [200]: /bundles/framework/css/structure.css
  ERR  [Fri Dec  4 05:20:18 2015] 127.0.0.1:60064 [200]: /bundles/framework/css/exception.css
  ERR  [Fri Dec  4 05:20:18 2015] 127.0.0.1:60065 [200]: /bundles/framework/css/body.css
  ERR  [Fri Dec  4 05:20:18 2015] 127.0.0.1:60066 [200]: /_wdt/f84516
  ERR  Segmentation fault
  ERR  
  RES  139 Command did not run successfully

                                                                                                                        
 [ERROR] Built-in server terminated unexpectedly. 
```

I tried the same code with *PHP7-FPM* & *Nginx* but it correctly displayed the syntax error. (See below) That's why I think it's a bug related to the *Symfony* server.
> Parse error: syntax error, unexpected '}'
> 500 Internal Server Error - FatalThrowableError

**Comment by javiereguiluz** [comment]
I think there is a problem with the code of your controller.

This line:

```php
$response = $this->render('')
```

should be:

```php
$response = $this->render('');
```

**Comment by Booteille** [comment]
It is, indeed. But why the Symfony server does he terminate just for a syntax error ?
Doesn't it should just return the syntax error and not stop the server ?

**Comment by jzawadzki** [comment]
I just tested it on php 5.6 and symfony/php server works fine (it doesn't make seg fault on problem like above - just normal 500) so ot looks like the issue may be with php7 version of server but I don't have now possibility to check it.

**Comment by stof** [comment]
If there is a segfault, it means there is a bug in PHP or one of the extensions, and so it should be reported to PHP.

**Comment by Booteille** [comment]
Yup, you are probably right. I just came here because it didn't segfault for the same script on Nginx based server.

**Comment by javiereguiluz** [comment]
@Booteille great! Closing this as "fixed" then. Thanks!

**Comment by stof** [comment]
@Booteille the PHP builtin webserver does not run the same code than php-fpm. But the webserver is **not** implemented by Symfony. ``server:run`` is just a wrapper to make things easier.

**Comment by Booteille** [comment]
Yup, I just saw this after searching sources of the server:run command. Thanks.
