### ISSUE TITLE
File redundancy

### ISSUE THREAD

**Issue by raulfraile** [symfony/symfony-installer#22]
Currently, the installer won't work if the symfony.com site is offline. Adding the option to download the file from other locations would help to minimize these issues. Some options to add redundancy:
1. Use the files provided by GitHub.
2. Mirrors, CDNs...
3. File-sharing services like Dropbox
4. Bit-torrent protocol (overkill for this project at it is now, but it might be useful in the future)

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because now that [Symfony Flex](https://github.com/symfony/flex) replaces the Symfony Installer, we won't add new features to the installer. Thanks for understanding it.
