### ISSUE TITLE
Before-update version number is wrong

### ISSUE THREAD

**Issue by SarramegnaG** [symfony/symfony-installer#230]
Hello,

I just installed symfony installer using windows command line :
```
D:\wamp\bin\symfony>php -r "file_put_contents('symfony', file_get_contents('https://symfony.com/installer'));"
D:\wamp\bin\symfony>php symfony --version
Symfony Installer version 1.1.7
```
Strangely, it downloaded version 1.1.7 instead of the lastest. So I decided to update it, it displayed that version 1.4.0 will be installed, but then when I checked version, it was 1.5.0.
```
D:\wamp\www>php symfony --version
Symfony Installer version 1.1.7

D:\wamp\www>php symfony selfupdate -vvv
// updating Symfony Installer to 1.4.0
 version

D:\wamp\www>php symfony --version
Symfony Installer version 1.5.0
```
Nothing serious, it's just strange.

Regards.

**Comment by ogizanagi** [comment]
There is a related discussion about that in #212

**Comment by javiereguiluz** [comment]
I'm closing it as fixed. We've made some change to the internal publishing workflow of the installer packages and everything seems to work as expected. I've just run `symfony self-update` and got the shiny new 1.5.1 version.

If it doesn't work for you, please reopen this issue. Thanks!
