### ISSUE TITLE
[RuntimeException]   Could not delete /tmp/.../Symfony/web/bundles/framework: rmdir(/tmp/.../Symfony/web/bundles/framework): Not a directory

### ISSUE THREAD

**Issue by pmaxs** [symfony/symfony-installer#235]
I got this error

> cd /var/www2
> symfony new qwerty

Downloading Symfony...
4.94 MB/4.94 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100%
Preparing project...

[RuntimeException]
Symfony can't be installed because the downloaded package is corrupted or because the installer doesn't have enough permissions to uncompress and rename the package contents. To solve this issue, check the permissions of the /var/www2 directory and try executing this command again: symfony new qwerty

[RuntimeException]
Could not delete /tmp/1453048451569bc2831e48f/Symfony/web/bundles/framework: rmdir(/tmp/1453048451569bc2831e48f/Symfony/web/bundles/framework): Not a directory

new <directory> [<version>]

> ls -a /tmp/1453048451569bc2831e48f/Symfony/web/bundles/framework

.  ..  css  images

> ls -all /tmp/1453048451569bc2831e48f/Symfony/web/bundles/framework

lrwxrwxrwx. 1 developer games 81 Jan 17 11:34 /tmp/1453048451569bc2831e48f/Symfony/web/bundles/framework -> ../../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/public/

Thanks

**Comment by Pierstoval** [comment]
Seems like the temp directory wants to delete an inexistent symlink :confused:

**Comment by joeckyeung** [comment]
Same as me.
I am using windows 7 and vagrant and docker.
but i can get into the symfony2 welcome page.

**Comment by skornev** [comment]
The problem with shared folders becuase it does not allow symlinks.

In home directory it works for me. 

Try 
```
cd /home
symfony new qwerty
```


But with
```
mv  qwerty /var/www2
```
I get
```
mv: cannot create symbolic link ‘/vagrant/www/qwerty/vendor/bin/doctrine’: Protocol error
mv: cannot create symbolic link ‘/vagrant/www/qwerty/vendor/bin/doctrine-dbal’: Protocol error
mv: cannot create symbolic link ‘/vagrant/www/qwerty/vendor/bin/doctrine.php’: Protocol error
mv: cannot create symbolic link ‘/vagrant/www/qwerty/vendor/bin/security-checker’: Protocol error
```



There are 4 ways to fix this 

1) use php symofony under windows and create symfony in shared folder
   ```
   php symfony new qwerty
   ```
2) stay with the box filesystem without syncing it
3) enable symlinks in shared folders
4) use composer

**Comment by Pierstoval** [comment]
What's the way to detect this specific case from inside of the installer?

**Comment by xabbuh** [comment]
I think this must be detected in Distill.

**Comment by sanceli** [comment]
Hi , when execute: php symfony new sf23 2.3 the installer is all Ok , i can see the welcome page for symfony version 2.3 
but when execute: php symfony new sf28 2.8 for version 2.8 the install show 2 rutime execpction as above, the persmisions are ok , symfony 2.3 install ok, Why do not install fine the version 2.8 ?

help please

php version is 5.6.24 on hostgator shared account

**Comment by javiereguiluz** [comment]
Closing this 2-year old issue because of the lack of activity and because Symfony Flex has made the Symfony Installer obsolete, so there's no need to fix this. Thanks!
