### ISSUE TITLE
Symfony Installer not functioning.

### ISSUE THREAD

**Issue by BonnieDoug** [symfony/symfony-installer#237]
Have just attempted to install and use the Symfony installer. 

I initially ran these two commands as statated in the docs:

    $ sudo curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony
    $ sudo chmod a+x /usr/local/bin/symfony

And then followed up by running:

    symfony new SymfonyApplicationName

Which resulted in this:

    Downloading Symfony...

    Fatal error: Cannot use lexical variable $eventName as a parameter name in phar:///usr/local /bin/symfony/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 48

Any thoughts on this would be great. I'm currently running the following on my system if it matters:

    PHP 7.1.0-dev (cli) (built: Jan 29 2016 15:06:17) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

**Comment by xabbuh** [comment]
Looks like an issue with Guzzle when used with PHP 7.1 (see guzzle/guzzle#1393).

**Comment by mbrig-co** [comment]
#21

**Comment by mbrig-co** [comment]
# **Please help!**
After successfully installing Symfony installer according to the instructions in its website, when I run the command `symfony new my_project` from my terminal it returned the following Guzzle exceptions:

```
user@linux-cdf0:/srv/www/htdocs> symfony new my_project

 Downloading Symfony...
                                                    
  [GuzzleHttp\Exception\RequestException]                                          
  No system CA bundle could be found in any of the the common system locations.    
  PHP versions earlier than 5.6 are not properly configured to use the system's    
  CA bundle by default. In order to verify peer certificates, you will need to     
  supply the path on disk to a certificate bundle to the 'verify' request          
  option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do not   
  need a specific certificate bundle, then Mozilla provides a commonly used CA     
  bundle which can be downloaded here (provided by the maintainer of cURL):        
  https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. Once    
  you have a CA bundle available on disk, you can set the 'openssl.cafile' PHP     
  ini setting to point to the path to the file, allowing you to omit the 'verify'  
  request option. See http://curl.haxx.se/docs/sslcerts.html for more              
  information.                                                                     
                                                                                                                                              
  [RuntimeException]                                                               
  No system CA bundle could be found in any of the the common system locations.    
  PHP versions earlier than 5.6 are not properly configured to use the system's    
  CA bundle by default. In order to verify peer certificates, you will need to     
  supply the path on disk to a certificate bundle to the 'verify' request          
  option: http://docs.guzzlephp.org/en/latest/clients.html#verify. If you do not   
  need a specific certificate bundle, then Mozilla provides a commonly used CA     
  bundle which can be downloaded here (provided by the maintainer of cURL):        
  https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt. Once    
  you have a CA bundle available on disk, you can set the 'openssl.cafile' PHP     
  ini setting to point to the path to the file, allowing you to omit the 'verify'  
  request option. See http://curl.haxx.se/docs/sslcerts.html for more              
  information.                                                                     
                                                                                   
new <directory> [<version>]
```

So what I have to do to work Symfony installer perfect for me?

**System** => Linux (OpenSuse Leap 42.1 x86_64)
**PHP Version** => 5.5.14
**Registered PHP Streams** => php, file, glob, data, http, ftp, compress.bzip2, https, ftps, compress.zlib, zip, phar
**Registered Stream Socket Transports** => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls
**OpenSSL support** => enabled

I don't know what else is needed.

**Note:** I did it by using Composer `composer.phar create-project symfony/framework-standard-edition` and it worked perfectly for me and downloaded Symfony 3.0.1

Thanks in advance,
Muhammad Nasir Rahimi

**Comment by javiereguiluz** [comment]
@mbrig-co it looks like you haven't configured properly the security certificates in your computer. The solution is simple:

1. Download this file https://curl.haxx.se/ca/cacert.pem and save it somewhere in your computer. for example, `~/cacert.pem`
2. Open your `php.ini` config file
3. Look for the following config and uncomment it if it exists or add it if it does not:

```ini
[curl]
curl.cainfo=~/cacert.pem
```

In any case, I'm closing this issue because it looks like Guzzle issues, so we can't fix them from the Symfony Installer. Thanks!

**Comment by AmaliDeveloper** [comment]
you can get the solution here https://youtu.be/gh1T8wS2alM
