### ISSUE TITLE
No warning/error given when installing Symfony 3.0 with PHP 5.4

### ISSUE THREAD

**Issue by Hornwitser** [symfony/symfony-installer#239]
Running

    $ symfony new my_project_name

as [suggested by the installation guide](http://symfony.com/doc/3.0/book/installation.html#creating-the-symfony-application) with PHP 5.4, will install Symfony 3.0, but issue no warnings or errors about the installation being incompatible with the PHP version used.  As documented in the [reference for Symfony 3.0](http://symfony.com/doc/3.0/reference/requirements.html) the minimum required version of PHP for Symfony 3.0 is 5.5.9.

This leads to a bad development experience as next thing suggested to do by the guide is to run the PHP development web server:

    $ php bin/console server:run
    PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 386

**Comment by javiereguiluz** [comment]
I agree. We should check if your PHP version is compatible with the Symfony version you want to install.

**Comment by jzawadzki** [comment]
@javiereguiluz - this should be already checked by requirements check after installation.
However, not sure why, on SymfonyRequirements.php file that we use, required version is still noted as 5.3.3: https://github.com/symfony/symfony-standard/blob/master/var/SymfonyRequirements.php#L379

**Comment by Pierstoval** [comment]
Maybe because we need to wait for a new build of all Symfony packages to take the new SensioDistributionBundle version (in which it should be fixed?)?

**Comment by javiereguiluz** [comment]
**Update about this issue**: instead of trying to fix it in the installer, it's better to let Symfony fix it upstream. There are some pending pull requests to fix it and we're just waiting for them to be merged. Thanks!

**Comment by jochenvw** [comment]
:+1: Yes please - I encountered this

**Comment by javiereguiluz** [comment]
Although this will be fixed in the future by Symfony, in #257 I propose a quick fix to prevent downloading a Symfony version that your system can't run.

**Comment by ptbello** [comment]
+1
