### ISSUE TITLE
Symfony installer pulls old symfony demo app.

### ISSUE THREAD

**Issue by sargath** [symfony/symfony-installer#240]
sargath ~/public_html/symfony_demo $ symfony  -V
Symfony Installer version 1.5.0

```
sargath ~/public_html $ symfony demo

 Downloading the Symfony Demo Application...

    6.68 MB/6.68 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony Demo Application was successfully installed. Now you can:

    1. Change your current directory to xxx/public_html/symfony_demo

    2. Execute the php app/console server:run command to run the demo application.

    3. Browse to the http://localhost:8000 URL to see the demo application in action.

sargath ~/public_html/symfony_demo $ app/console -V
Symfony version 2.7.6 - app/dev/debug
```

**Comment by sargath** [comment]
I think that it might be related to method 

```php
   protected function getRemoteFileUrl()
    {
        return 'http://symfony.com/download?v=Symfony_Demo';
    }

```

Because when I go by hand to http://symfony.com/download?v=Symfony_Demo.tgz 
It downloads Symfony version 2.7.6 - app/dev/debug

So url does not provide highest version of demo app though.

**Comment by stof** [comment]
That's really weird, as the latest version of the demo uses Symfony 2.8.2

@javiereguiluz can you check this ? This looks like an issue on symfony.com where it uses an old archive

**Comment by javiereguiluz** [comment]
Yes, this is an issue on our side. I can't estimate the time it will take us to solve this, but I hope it's sooner than later. Thanks.

**Comment by javiereguiluz** [comment]
Gladly closing this as "fixed". The `symfony demo` command now installs the most recent Symfony Demo version. Thanks!

**Comment by sargath** [comment]
@javiereguiluz are you sure about this ? I've just try it and :


```
sargath ~/public_html $ symfony -V
Symfony Installer version 1.5.0
sargath ~/public_html $ symfony demo

 Downloading the Symfony Demo Application...

    6.68 MB/6.68 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony Demo Application was successfully installed. Now you can:

    1. Change your current directory to /home/sargath/public_html/symfony_demo

    2. Execute the php app/console server:run command to run the demo application.

    3. Browse to the http://localhost:8000 URL to see the demo application in action.


sargath ~/public_html $ cd symfony_demo
sargath ~/public_html/symfony_demo $ app/console -V
Symfony version 2.7.6 - app/dev/debug
sargath ~/public_html/symfony_demo $ 
```

**Comment by sargath** [comment]
...also http://symfony.com/download?v=Symfony_Demo.tgz downloading still same sized archive

**Comment by javiereguiluz** [comment]
I've just tested and it works for me. I didn't update the Symfony Installer and I didn't do anything special:

![symfony_demo_updated](https://cloud.githubusercontent.com/assets/73419/14182641/7c520cb6-f76c-11e5-8bf9-1ff712f4f909.png)

**Comment by sargath** [comment]
@javiereguiluz  hmmm that is weird ... but i found that if  I use link with *.tgz it goes with old version but using http://symfony.com/download?v=Symfony_Demo.zip I'm getting 2.8.4-DEV so it might be related what Distill that is selecting package type regarding to OS or something.

**Comment by sargath** [comment]
@javiereguiluz additionally I'm on archlinux OS

**Comment by sargath** [comment]
@javiereguiluz I think from today it is OK, now the right version is being downloaded

**Comment by javiereguiluz** [comment]
@sargath cool! If you have any other problem, please ping me because we'd like to monitor this issue very closely. Thanks!
