### ISSUE TITLE
proxy is not used everywhere

### ISSUE THREAD

**Issue by brightdroid** [symfony/symfony-installer#243]
In some places the installer still use "file_get_contents", which does not work behind a proxy.
e.g.
- DownloadCommand::createGitIgnore
- SelfUpdateCommand...
- ...

**Comment by mariuspuiu** [comment]
It might be linked to my issue #242 also.
I am behind a proxy but with `cURL` it works.

**Comment by brightdroid** [comment]
Indeed! Sorry, didn't found your issue.
