### ISSUE TITLE
Some methods and class attributes don't have DocBlock

### ISSUE THREAD

**Issue by regniblod** [symfony/symfony-installer#251]
I've seen that some classes have DocBlock in their attributes, e.g. [this one](https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/DownloadCommand.php), while other classes don't have it, e.g. [this one](https://github.com/symfony/symfony-installer/blob/master/src/Symfony/Installer/AboutCommand.php). Is it for any reason in particular?

I would be happy to submit a PR fixing it if it's not intended.

**Comment by javiereguiluz** [comment]
@regniblod there is no reason except that the class is simple and we forget about it. So, if you submit a PR for this or any other missing dockblock, we'll gladly merge it. Thank you very much!

**Comment by regniblod** [comment]
Submitted PR #252.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #252.
