### ISSUE TITLE
bin/console server:run throws Segmentation Fault with twig template errors

### ISSUE THREAD

**Issue by xserrat** [symfony/symfony-installer#258]
Hi,

I had an error about `bin/console server:run` execution. The problem occurs when I was trying to render a twig template with the following `copy/paste` error:

```html
{% extends 'AcmeBundle:Default:base.html.twig' %}

{% block body %}

<h1>Hello world</h1>

{% endblock %}
```
_This file corresponds to AcmeBundle/Resources/views/Default/base.html.twig_

So, because of the template **extends from itself**, when the built-in web server serves this template, a Segmentation Fault is thrown:

```zsh


  [Symfony\Component\Process\Exception\RuntimeException]
  The process has been signaled with signal "11".


server:run [-p|--port PORT] [-d|--docroot DOCROOT] [-r|--router ROUTER] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<address>]

```

And if I try to use `php -S localhost:8000` :

```zsh
[1]    5583 segmentation fault  php -S localhost:8000

```

**Comment by Pierstoval** [comment]
If you have an error because a template extends from itself, then you know how to solve the error...

**Comment by xabbuh** [comment]
Segmentation faults are errors in PHP itself or in one of the extensions you use and nothing wer can fix in Symfony. That's why I am closing here.

**Comment by javiereguiluz** [comment]
@xabbuh you are right about *"we can't do nothing for segfaults"* ... but we could do something to prevent that segfault. @xserrat said that this error is because a Twig template is (by mistake) extending from iteself. Shouldn't Twig/Symfony/Templating detect this kind of errors and display a good error message instead?

**Comment by Pierstoval** [comment]
The first thing would be IMO to make sure a template does not extend itself, because it makes no sense to create an infinite loop :confused:

**Comment by xserrat** [comment]
Exactly @javiereguiluz, I thought that the mistake would be detected and symfony shows an error message.

**Comment by javiereguiluz** [comment]
@xserrat cool! I've opened this issue in the Symfony repo to try to improve this: https://github.com/symfony/symfony/issues/19018

**Comment by javiereguiluz** [comment]
@xserrat sadly this proposal was rejected. I'm terribly disappointed by this decision. I'm sorry.

**Comment by xserrat** [comment]
@javiereguiluz thank you very much for your proposal! Don't worry, we'll have to attend in order to avoid this type of mistakes :)
