### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by bm93** [symfony/symfony-installer#260]
trying to install symfony 3.1 and when i use the command "php symfony new my_project" i get 
![capture](https://cloud.githubusercontent.com/assets/20112334/16309956/787438f2-3962-11e6-88d7-ea56894e27e9.JPG)

**Comment by xabbuh** [comment]
looks like this is the same as #249

**Comment by antoniogarcia78** [comment]
We have the same problem. I change PHP version from 7.0.5 to 5.6 and now work perfect.

Javier Eguiluz explain in the issue https://github.com/symfony/symfony-installer/issues/237 a solution to a similar problem with cURL. 

Maybe you can try.

**Comment by antoniogarcia78** [comment]
Second round. 
Symfony installer force me to selfupdate and now i have the same error with PHP 5.6
To fix the problem follow the solution of Javier Eguiluz in the issue #237 
I use xampp and i configure then

`curl.cainfo=c:/xampp/php/cacert.pem`

Good night

**Comment by bm93** [comment]
thanks guys problem fixed

**Comment by AmaliDeveloper** [comment]
you can get the solution here https://youtu.be/gh1T8wS2alM
