### ISSUE TITLE
self-update command throws fatal error on PHP 7.1 

### ISSUE THREAD

**Issue by nifr** [symfony/symfony-installer#263]
I get the following error when trying to run  `self-update` with the phar version of the installer:

```
PHP Fatal error:  Cannot use lexical variable $eventName as a parameter name in phar:///home/username/.local/usr/share/php/phar.d/symfony.phar/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 48
```
File permissions are `0700`, owner and group are correct.

I'm using the latest **php7.1** package from **ppa:ondrej/php** on Ubuntu 16.04 Xenial with Symfony Installer version **1.5.4**. 

> 
> PHP 7.1.0alpha2 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.1.0alpha2, Copyright (c) 1999-2016, by Zend Technologies

Using **update-alternatives** to switch to php7.0 fixes the issue.

> sudo update-alternatives --config php
> php -v 
> 
> PHP 7.0.8-3+deb.sury.org~xenial+1 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.8-3+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
>     with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
> 
> symfony self-update
> // Symfony Installer is already updated to the latest version (1.5.4).

**Comment by xabbuh** [comment]
see #237 and guzzle/guzzle#1393

@symfony/deciders It doesn't look like Guzzle will get a new release of the `5.3` branch anytime soon. What do we do here? Update to an unstable Guzzle version?

**Comment by fabpot** [comment]
Let's update to an unstable version for now

**Comment by weaverryan** [comment]
+1 for going to the latest (untagged), unstable 5.3 branch to get the fix.

**Comment by xabbuh** [comment]
@nifr Can you check if #265 fixes the issue for you?
