### ISSUE TITLE
The suhosin PHP extension causes symfony-installerto not output anything

### ISSUE THREAD

**Issue by bobningx** [symfony/symfony-installer#264]
The PHP extension  "suhosin" cause symfony-installer doesn't output anything, and it's no easy to find that reason.

It would be better to add "suhosin" detect in symfony-installer or add this notice  at the symfony's intall page "http://symfony.com/download", 

thanks

system info:  openSUSE Leap 42.1 (x86_64),
php5-5.5.14-53.1.x86_64.rpm
php5-phar-5.5.14-53.1.x86_64.rpm
php5-suhosin-5.5.14-53.1.x86_64.rpm

**Comment by javiereguiluz** [comment]
Closing it as fixed by #275.
