### ISSUE TITLE
Outdated Version

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony-installer#267]
$ curl -LsS https://symfony.com/installer -o symfony
$ chmod a+x symfony
$ ./symfony new my_project
>   WARNING  Your Symfony Installer version (1.5.5-DEV) is outdated.
>  Execute the command "./symfony selfupdate" to get the latest version (1.5.5).

**Comment by xabbuh** [comment]
Maybe related to #266?

**Comment by Archmonster** [comment]
Yes, fixing #266 should fix this too.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #266. If the error persists, please reopen. Thanks!
