### ISSUE TITLE
Fix "cURL error 60: SSL certificate problem"

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#268]
- It only happens on Windows systems
- It's causing lots of different issues:
  - `.gitignore` is not downloaded when creating a project (#249)
  - PHPStorm can't create Symfony projects (https://github.com/symfony/symfony/issues/19360)
  - ...

**Comment by sstok** [comment]
Tip to give when this happens, "Check if your antivirus has SSL scanning enabled, disable this and try again."

SSL scanning places the antivirus software's CA in the middle so content can be scanned before it's delivered. However, you are required to install the CA in the certs store of the system, which of course doesn't work for Guzzle (depending on which version you are using).

*Not to mention that SSL scanning completely breaks the trust model of PKI.. 💀*

**Comment by Pierstoval** [comment]
I could solve this issue both in Composer and Symfony installer with this bundle of root certificates:

https://curl.haxx.se/ca/cacert.pem

Just had to register them in my Windows certificates manager.

**Comment by QuantumRevenger** [comment]
"Check if your antivirus has SSL scanning enabled, disable this and try again." - doesn't seem to work even after disabled Webroot A/V.

@Pierstoval could I get a second opinion on this solution because the domain is haxx.se and I'm a little cautious about installing CA/Certs into my Windows Manager.

**Comment by Pierstoval** [comment]
@QuantumRevenger These certs were extracted from Mozilla sources coming from their wiki: https://wiki.mozilla.org/CA:IncludedCAs. You can just include them in your php conf instead of windows if you like.

**Comment by sstok** [comment]
Ah wait I remember 🤔 SSL with PHP on Windows until version 5.6 was horribly broken (CA file not properly detected "Fallback to Windows CA cert store for peer verification if no openssl.cafile ini directive or "cafile" SSL context option specified in Windows.").

Guzzle did solve this, but it will only work when the files are up-to-date.
https://github.com/guzzle/RingPHP/blob/9465032ac5d6beaa55f10923403e6e1c36018d9c/src/Client/ClientUtils.php#L36-L37

**Comment by QuantumRevenger** [comment]
@sstok would that mean, if the latest Guzzle update was merged into the Symfony installer it would potentially resolve the problem?

I'm going to create a fork/branch from the installer and give it a try anyway and report back, if it works I'll report back with the fix.

**Comment by sstok** [comment]
The Symfony installer is using the latest Guzzle, but the detection will only work **"when the files are up-to-date"**, that being the SSL CA files as searched in https://github.com/guzzle/RingPHP/blob/9465032ac5d6beaa55f10923403e6e1c36018d9c/src/Client/ClientUtils.php#L36-L37

**Comment by Haehnchen** [comment]
yes, PhpStorm is using Symfony Installer, but problem occurs after updates on the installer. guzzle changes looks suitable; not having cert files in a default Windows installations

**Comment by ma-gu-16** [comment]
Hi, 

i solved this too. 

`http://curl.haxx.se/ca/cacert.pem  (THX Pierstoval)`

download the pem file and save it in your php installation directory 

and now edit your php.ini and write the following at the end of file:

```
[cURL] 
curl.cainfo="C:\XAMPP\php\cacert.pem"
```

be sure that you write the correct path. 

after i added the cert it works very well. 

hope this was usefull.

**Comment by sstok** [comment]
⚠️ **Warning never download a CA chain over plain HTTP! Use the HTTPS version instead.** ⚠️
https://curl.haxx.se/ca/cacert.pem

**Comment by AmaliDeveloper** [comment]
you can get the solution here https://youtu.be/gh1T8wS2alM

**Comment by javiereguiluz** [comment]
Closing as fixed by the instructions displayed by @ma-gu-16.

**Comment by SEMeesha** [comment]
This maybe helpful
https://www.youtube.com/watch?v=plc7T4HCJSk&t=19s

**Comment by saifrehman15** [comment]
This solve the problem. 
https://stackoverflow.com/questions/42094842/curl-error-60-ssl-certificate-in-laravel-5-4
