### ISSUE TITLE
Outdated installers are wrongly detected

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#274]
After upgrading to the recent 1.5.7 version, the installer strangely exposes itself as `1.5.7-DEV`. This makes the installer to display this message whenever you execute a command:

![symfony_installer_version](https://cloud.githubusercontent.com/assets/73419/17135226/f5d382c2-532e-11e6-88fd-39550fc75319.png)

**Comment by Pierstoval** [comment]
Just exploore the `v1.5.7` tree and check this file:
https://github.com/symfony/symfony-installer/blob/v1.5.7/symfony
The hardcoded version is appended with `-dev`.

Hardcoded version **must** be correct when building a new version. Can you replace the tag with a correct one?

**Comment by javiereguiluz** [comment]
@Pierstoval thanks for your help. I follow a checklist when releasing a version, so I don't know how that could happen 😞 

I'm going to release a new version because I'm not sure that we regenerate the installer binary if we update but not create a tag.

**Comment by Pierstoval** [comment]
I'm curious: do you have this checklist somewhere?

**Comment by javiereguiluz** [comment]
@Pierstoval yes ... and you know it well --> https://github.com/javiereguiluz/EasyAdminBundle/blob/master/.github/RELEASE_CHECKLIST.md I just skip the steps irrelevant for this project.

**Comment by javiereguiluz** [comment]
Closing it as fixed by the recent 1.5.8 release.
