### ISSUE TITLE
Fix test errors in PHP 5.4

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#280]
There are some fails when running tests on PHP 5.4 (other PHP versions work fine). Could anyone take a look at it and help us fix it? Thanks!

Here are the details of this error: https://travis-ci.org/symfony/symfony-installer/jobs/165459664

**Comment by lyrixx** [comment]
[Box](https://github.com/box-project/box2/blob/2.0/composer.json#L28) is using symfony `~2.1 || ~3.0` so 3.1.* and symfony 3+ requires php 5.5+. that's why the box build did not work.

**Comment by stof** [comment]
what you could do is running box with a different php version for this job:

```
~/.phpenv/versions/5.6/bin/php box build
```

PHP 5.6 is preinstalled in Travis images, so you can use it even when it is not the main version

**Comment by javiereguiluz** [comment]
Closing it as fixed by #281.  Guys, thanks for your help. The proposed solution worked like a charm!
