### ISSUE TITLE
Integration test's of master branch fail

### ISSUE THREAD

**Issue by mariotux** [symfony/symfony-installer#286]
I'm checking the project. The first thing I do is launch the tests.
 In master branch the test: `testDemoApplicationInstallation`

1.- now exists a Symfony 3.x.x-BETA1 and the _**assertRegExp**_ must be:
`$this->assertRegExp('/Symfony( version)? 3\.\d+\.\d+(-(DEV|BETA\d+))? (- app\/dev\/debug|\(kernel: app, env: dev, debug: true\))/', $output);`
2.- in the assertArrayNotHasKey I don't know if it has to be this way, but when the version is BETA the composer.json doesn't has "config" and after this line:
`$composerConfig = json_decode(file_get_contents($projectDir.'/composer.json'), true);`
The array $composerConfig doesn't has config key.

I would make a PR but I don't know how  has to be the second point.

Regards,

**Comment by javiereguiluz** [comment]
Tests were finally fixed as part of #295.
