### ISSUE TITLE
IntegrationTest use symfony.phar build

### ISSUE THREAD

**Issue by mariotux** [symfony/symfony-installer#287]
I think is not necessary to use a build of symfony.phar to launch the integration tests. 
```php
 public function setUp()
    {
        $this->rootDir = realpath(__DIR__.'/../../../../');
        $this->fs = new Filesystem();

        if (!$this->fs->exists($this->rootDir.'/symfony.phar')) {
            throw new \RuntimeException(sprintf("Before running the tests, make sure that the Symfony Installer is available as a 'symfony.phar' file in the '%s' directory.", $this->rootDir));
        }
    }
```
If we use the symfony script file is better than the build of phar, because the symfony.phar not must be in the repository, and is not a good idea to build the phar file in the setUp of test.

Of this way we can work and launch integration test of project, without build the project to launch integration test. Build the symfony.phar for integration test I think is redundant.

If you are agree I can make a simple PR.

Regards,

**Comment by Pierstoval** [comment]
The phar file is built on travis-ci only (check [.travis.yml](https://github.com/symfony/symfony-installer/blob/master/.travis.yml) file for more info). It sounds relevant to me because it pushes the tests very close to "production" tests, because everyone will use the phar _in fine_, not the repo binary.

**Comment by stof** [comment]
well, using the phar is done on purpose, to ensure that the phar itself is working (it also catches mistakes in the phar building itself, which happened in the past).
So I'm closing this issue
