### ISSUE TITLE
Segmentation fault while running built-in server

### ISSUE THREAD

**Issue by Leggy7** [symfony/symfony-installer#289]
I'm facing a weird behavior while executing this preRemove event callback

```
public function preRemove(LifecycleEventArgs $args){
    $entity = $args->getEntity();

    if(!$entity instanceof Image){
      return;
    }
    $em = $args->getEntityManager();
    $entity->setParent(null);
    $em->merge($entity);
    $em->flush();
  }
```
The error occurs if the `flush()` is executed.

Then the server crashes with the following error

> [...]
> Press Ctrl-C to quit.
> Segmentation fault (core dumped)
>                                                                                 
>  [ERROR] Built-in server terminated unexpectedly. 

I'm running it with php 5.6 on ubuntu 16.10.

Any suggestion?

**Comment by Pierstoval** [comment]
This issue should be moved to @Symfony/symfony instead.

And by the way, can you use `gdb php bin/console server:run` or `php -d xdebug.auto_trace=ON -d xdebug.trace_output_dir=__any directory__ bin/console server:run` to track the segfault and add the output to your issue message?

**Comment by javiereguiluz** [comment]
Closing as probably unrelated to the Symfony Installer. It looks like a Symfony code issue.
