### ISSUE TITLE
specify different tmp dir

### ISSUE THREAD

**Issue by mrbase** [symfony/symfony-installer#292]
It would be great if you could set a different [downloadedFilePath](/symfony/symfony-installer/blob/master/src/Symfony/Installer/DownloadCommand.php#L180)

**Comment by Pierstoval** [comment]
Why exactly? Did you encounter a particular issue when installing Symfony?

**Comment by mrbase** [comment]
edge case I know - but we wanted to create new sites via a user who do not have write access to its home directory

**Comment by stof** [comment]
then overwrite the HOME variable before calling the command, to make the installer believe that the HOME is somewhere else (and make sure this place is writable) 😄

**Comment by stof** [comment]
Actually, this file is not even downloaded in the home. It is downloaded in the current working dir. 
And to create a new project, you need to be in a place where you can write anyway.

**Comment by mrbase** [comment]
yeah - it occurred to me alså @stof - will close the issue here and rewrite the caller instead.
