### ISSUE TITLE
Wrong composer.json after installation 

### ISSUE THREAD

**Issue by skornev** [symfony/symfony-installer#294]
How to reproduce
```
symfony new test
./bin/console generate:bundle --namespace=Acme/Bundle/BlogBundle --no-interaction
./bin/console generate:bundle --namespace=Acme/Bundle/BlogBundle2 --no-interaction
[RuntimeException]

  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Class 'Acme\Bundle\BlogBundle\AcmeBundleBlogBundle' not found in /home/icustoms/test/app/AppKernel.php on line 19
```

The issue 
The problem is that autoloader is not aware of  the created new bundle  .

How to fix:
add "src" to composer.json or  symfony generator should be rewritten to add each Bundle to psr-4
 "psr-4": {
            "AppBundle\\": "src/AppBundle",
             "":"src"
        },

**Comment by Pierstoval** [comment]
This iis not a problem of the installer but of [SensioGeneratorBundle](https://github.com/sensiolabs/SensioGeneratorBundle).
