### ISSUE TITLE
vagrant symfony installer problem

### ISSUE THREAD

**Issue by bartek1234321** [symfony/symfony-installer#296]
hi, i've got problem with symfony installer(version (1.5.9)) on vagrant, when execute command: symfony new project 2.8 during 34% of progress the error is occurring:

Warning:  include(phar:///usr/local/bin/symfony/vendor/composer/../guzzlehttp/guzzle/src/Exception/RequestException.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/symfony" (actual filesize mismatch on file "vendor/guzzlehttp/guzzle/src/Exception/RequestException.php") in phar:///usr/local/bin/symfony/vendor/composer/ClassLoader.php on line 414
PHP Stack trace:
...
PHP Warning:  include(): Failed opening 'phar:///usr/local/bin/symfony/vendor/composer/../guzzlehttp/guzzle/src/Exception/RequestException.php' for inclusion (include_path='.:/usr/share/php') in phar:///usr/local/bin/symfony/vendor/composer/ClassLoader.php on line 414
PHP Stack trace:
...
PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Exception\RequestException' not found in phar:///usr/local/bin/symfony/vendor/guzzlehttp/guzzle/src/RequestFsm.php:102

**Comment by javiereguiluz** [comment]
I'm afraid this error is out of the scope of this tool because it's about a *"internal corruption of phar"* and the errors are displayed by GuzzleHttp. I'm sorry.
