### ISSUE TITLE
Wrong key name for SQLite database path

### ISSUE THREAD

**Issue by vfranca** [symfony/symfony-installer#297]
In the app/config/config.yaml file the key name for the SQLite database path looks like this:

```yml
# e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
```
But the correct name is:

```yml
# e.g. path: '%kernel.project_dir%/var/data/data.sqlite'
```

**Comment by chalasr** [comment]
I guess you are referring to https://github.com/symfony/symfony-standard/blob/3.3/app/config/config.yml. 
In fact, it does tell to use `database_path` as key, but recommends to set a `database_path` parameter to use as `path: %database_path%`.

**Comment by vfranca** [comment]
Thank you,
You are right.
I have not noticed that the database_path key is only used in the parameters.yml file.
It's all right. Sorry.
