### ISSUE TITLE
The selected version (latest) cannot be installed because it does not exist

### ISSUE THREAD

**Issue by modiniks** [symfony/symfony-installer#298]
I have the latest version of the installer downloaded today.

[RuntimeException]
The selected version (3.3.12) cannot be installed because it does not exist.
Execute the following command to install the latest stable Symfony release:
symfony new apidemo

I used the same command to create new project. I tried creating new project with earlier versions too.
Its giving me same error with version changed.

I am using xampp with windows 10. It was working last week.

**Comment by Juanchote** [comment]
same for me... mac osx here.

**Comment by asha-tkp** [comment]
I am facing the same issue when creating a new project with latest version.
![screenshot from 2017-11-14 11-58-23](https://user-images.githubusercontent.com/17933900/32769035-b653aec0-c933-11e7-95a8-1c20667e0d5f.png)

![screenshot from 2017-11-14 11-58-57](https://user-images.githubusercontent.com/17933900/32769040-b91fb7e8-c933-11e7-8849-554ca28def0b.png)

![screenshot from 2017-11-14 11-59-11](https://user-images.githubusercontent.com/17933900/32769045-be11b530-c933-11e7-8e58-4570c1f839d7.png)

**Comment by Jomateix7** [comment]
Same issue, having on an Ubuntu installation.

**Comment by BleuDiamant** [comment]
Oh what a coincidence i have the same problem on : 
Windows 10 Professional - 64bits 
PHP 7.0.24
Symfony.phar 1.5.9
I already updated my cacert.pem and my symfony.phar.
At this time the only version that i found who work for me is 3.3.11 and 2.7.30.

**Comment by symio** [comment]
I found a manner to get 3.3.12 :
- install via composer : composer create-project symfony/framework-standard-edition urProjectName "3.3.*"
it install a 3.3.11
then move to the project and run composer update

Now you've got a fresh 3.3.12 (tx Sensio for the comment on FB ;) )

**Comment by xabbuh** [comment]
The easier solution though is to run `symfony new directory-name 3.3.11` and afterwards run `composer update symfony/symfony`.

**Comment by cjsfj** [comment]
We are able to do a symfony install based on a version, but not an install based on a branch:

``symfony new ./pathtoapp 2.8``

fails. However

``symfony new ./pathtoapp 2.8.30``

is successful.

**Comment by xabbuh** [comment]
I am closing here as this is working again.
