### ISSUE TITLE
Gentle deprecation of this tool

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-installer#300]
This idea was proposed by @weaverryan on the Symfony Slack chat:

-----

This installer is deprecated starting from Symfony 4. We could do a last release of the installer to default to 3.4 and print a big warning message when trying to install Symfony 4.

Currently `symfony new blah` fails with `The selected version (4.0.1) cannot be installed...`

**Comment by KhanMaytok** [comment]
Why is this tool deprecated?

**Comment by Pierstoval** [comment]
Because Flex is the new way to create Symfony projects

**Comment by weaverryan** [comment]
Ping! We should still do this. There is confusion by this not working now in some cases.
