### ISSUE TITLE
can't create the global symfony cmd in powershell

### ISSUE THREAD

**Issue by runiArnsbjornson** [symfony/symfony-installer#304]
i have an issue with the command needed to install symfony as a global cmd because powershell won't allow & to be used : 

```
PS D:\bin > (echo @ECHO OFF & echo php "%~dp0symfony" %*) | Out-File outputfile -encoding ASCII symfony.bat
Au caractère Ligne:1 : 17
+ (echo @ECHO OFF & echo php "%~dp0symfony" %*) | Out-File outputfile - ...
+                 ~
Le caractère perluète n’est pas autorisé. L’opérateur & est réservé à une utilisation future. Placez un caractère perluète
entre guillemets doubles ("&") pour que ce symbole soit considéré comme une chaîne.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

does anyone know how i can solve this, i'm at my wits end

**Comment by Pierstoval** [comment]
You can create a `symfony.bat` in your `%PATH%` containing this:

```cmd
@echo OFF
php "%~dp0symfony" %*
```

No need for the command-line.

If you still need powershell, just know that the `& echo` trick is valid only under `cmd`. For Powershell, you have to use the `` `n `` trick, the backtick acting as an escaping character:

```cmd
> (echo "@ECHO OFF `nphp `"%~dp0symfony`" %*") | Out-File outputfile -encoding ASCII symfony.bat
```

**Comment by javiereguiluz** [comment]
@runiArnsbjornson did @Pierstoval comment fixed your problem?

**Comment by runiArnsbjornson** [comment]
oh yeah ^^ 
sorry it works perfectly now, forgot to say it was solved
