### ISSUE TITLE
Display available symfony version

### ISSUE THREAD

**Issue by armetiz** [symfony/symfony-installer#306]
Hi there.

Could be cool to see available versions using CLI

```bash
symfony versions
```

**Comment by Pierstoval** [comment]
Was refused in #202, #106 and #82.

You can check the [official roadmap](https://symfony.com/roadmap) if needed, or see the [versions.json](https://symfony.com/versions.json) file.

**Comment by javiereguiluz** [comment]
@armetiz although it was rejected in the past, we could have reconsider this decision if enough people asked for it. Problem is that we "ended" the Symfony Installer a few days ago (see https://symfony.com/blog/the-end-of-the-symfony-installer). That means that we'll continue fixing bugs, but we can't add any new feature. I'm sorry.

**Comment by armetiz** [comment]
no problem,
