### ISSUE TITLE
create_function() is depcreated in PHP7.2

### ISSUE THREAD

**Issue by alpha1125** [symfony/symfony-installer#307]
at the bash prompt
$> symfony new myproject 3.4
...
PHP Deprecated:  Function create_function() is deprecated in [redacted]/var/SymfonyRequirements.php on line 540

line 558
line 707

**Comment by alpha1125** [comment]
Just realized, that this maybe the wrong location to put this. Does anyone know where it should go?

**Comment by jakzal** [comment]
SymfonyRequirements.php is part of https://github.com/sensiolabs/SensioDistributionBundle

For Flex this has been fixed already in https://github.com/symfony/requirements-checker/pull/11.
