### ISSUE TITLE
Incompatible with Symfony 4 or newer

### ISSUE THREAD

**Issue by Aerogirl10** [symfony/symfony-installer#312]
At plugins.jetbrains.com describtion is written that it supports "Symfony 2, 3, 4…" but after creating project in PHPStorm i get this 

> The Symfony Installer is not compatible with Symfony 4.x or newer versions. Run this other command to install Symfony using Composer instead: composer create-project symfony/skeleton .checkout new

Is it going to be fixed or if I want to use only newest version I need to say "bye" to this plugin?

**Comment by xabbuh** [comment]
Which plugin do you refer to? If you mean [the Symfony plugin](https://plugins.jetbrains.com/plugin/7219-symfony-plugin), that one is still compatible with Symfony 4, you just need to change the way you start a new project (see https://github.com/symfony/symfony-installer#creating-symfony-4-projects for more details).
