### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by ekyna** [symfony/symfony-installer#313]
Apologies, this is not code related but i don't know where to post this elsewhere.

I just installed the symfony installer. It tooks 20 mins at ~15 KB/sec (I have a ~300Mbs bandwidth). Perhaps you could improve the download speed ?

![symfony-installer-speed](https://user-images.githubusercontent.com/3483641/51426002-889d1480-1be4-11e9-834b-caf6c335a6ff.png)

**Comment by javiereguiluz** [comment]
That's strange. We use Amazon's AWS CDNs to serve these static files, so there shouldn't be any problem with the download speed.

Could you please tell us the exact steps you followed to install Symfony? Maybe you are using the legacy abandoned installer? Or did you followed the steps explained in https://symfony.com/download?

**Comment by ekyna** [comment]
I followed the steps on the symfony download page you linked.

**Comment by javiereguiluz** [comment]
Do you experience the same slow download speed anytime you try to download the installer? Maybe it was a temporary network issue?

**Comment by ekyna** [comment]
Apologies. My antivirus (NOD32 Internet Security) was slowing down the download. Disabling protection allowed me to download at full speed.
