### ISSUE TITLE
[CLI 4.2.6][Symfony 3.4] The installer created the project with incomplete code

### ISSUE THREAD

**Issue by zacharyzh** [symfony/symfony-installer#314]
Today I created a new symfony project using version 3.4, And I got an incomplete code without any warnings. it contains only 2 dirs: config and vendor. 

    symfony new --full --version=3.4 ./3.4

But when I executed the same install command for the second time, everything was (looks like) fine.

![sf1](https://user-images.githubusercontent.com/4945538/51525563-91534c00-1e6b-11e9-81ea-cda9813c01a4.png)
![sf2](https://user-images.githubusercontent.com/4945538/51525570-96b09680-1e6b-11e9-80b9-0a6d10e0417c.png)

Edit: no any other operations between 2 commands execution.

**Comment by Pierstoval** [comment]
If you used the installer from SymfonyCloud, I suggest you copy/paste your ticket to https://github.com/symfonycorp/symfony-cli-issues 😉

**Comment by Pierstoval** [comment]
It's just that since SfCloud was released, it became "the" Symfony installer, but it should be usable without SymfonyCloud features itself.

This repository is for the "old" symfony installer that was used for Symfony 3 projects 😉

**Comment by zacharyzh** [comment]
@Pierstoval Thank you for your explanation.

For now I am sure about that this issue was caused by network issues, so I am using a proxy on Composer and now everything is fine.

Closing this issue because of the reasons above. 😊
