### ISSUE TITLE
A better way to manage the version of Symfony the user want to install

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-installer#42]
Right now, the version must be a precise version like 2.3.20 or 2.5.5.

I could be useful to also allow versions like 2.3 or 2.5 (that would install the latest version of these versions.)

Less interesting but potentially useful, allow a special 'lts' version.

To be able to do that, we should create a new endpoint on symfony.com: http://symfony.com/versions.json where we reference all this information.

Having this information would also allow us to better validate versions provided by the user.

@javiereguiluz Can you work on that especially for the symfony.com side?

**Comment by WouterJ** [comment]
Is this not fixed by #90 ?

**Comment by Pierstoval** [comment]
I think @javiereguiluz merged the PR #90, but this commit has not been part of any new release yet, I think.

**Comment by javiereguiluz** [comment]
@Pierstoval you are right: this is merged, but a new release of the installer has to be done.

**Comment by WouterJ** [comment]
Can't we make the installer a continues release? (or at least a quick release circle)

**Comment by Pierstoval** [comment]
I don't think that the installer needs many features enough to make a continuous release system, because when the installer is "complete", we'll only have to fix some bugs, and maybe adapt some times with SF2 next releases (which occures twice a year).
And whenever SF3 comes, there's probably gonna be some fixes too :)

**Comment by javiereguiluz** [comment]
I agree with @Pierstoval. In fact, I think that the installer is already finished (after the next release) and we shouldn't add any other feature to it.

**Comment by Pierstoval** [comment]
Any kind of additional feature would then transform the "Installer" into a complete "App manager".
We can think about some commands like `symfony check` or many other good tools, which will use some Sensio tools to check if the project is clean, etc, but as said, it would go out of the "Installer" specific feature :smile:, and probably would be integrable as a composer dependency :+1:

**Comment by WouterJ** [comment]
The installer has 12 issues, 6 bugs and currently supports only the SE (no starters sandbox, no other official editions like CMF and Rest). I think you shouldn't call it finished.

**Comment by 94noni** [comment]
@fabpot 

> Less interesting but potentially useful, allow a special 'lts' version.

see https://github.com/symfony/symfony-installer/pull/105

**Comment by Pierstoval** [comment]
Now that we have short semantic version and lts, I think this issue is solved, isn't it?

**Comment by javiereguiluz** [comment]
@Pierstoval you are right. Let's close this issue.
