### ISSUE TITLE
Set proper permissions for app/cache and app/logs

### ISSUE THREAD

**Issue by scuben** [symfony/symfony-installer#61]
I often face the problems that i need to set up proper permissions to app/cache and app/logs to be writeable by me (machine user) and the webserver. There is the info about it on the symfony doc (link: http://symfony.com/doc/current/book/installation.html#configuration-and-setup) but i always need to go there and copy paste the commands.

It would be nice to ether have one of the following solutions:
* als the user if he want to set permissions. If yes: ask them how they want to be done (acl chmod +a, acl, umask)
* add an option to the installer where you can specify the permission type you want to use

I think not to bother users that are not aware of this problem or even dont have it (same user for cli and webserver) the way to go would be to add an option to the sf installer.

What do you think about that?

**Comment by javiereguiluz** [comment]
I agree with @sr972. We already have a lot of permissions issues for the installer (e.g. people execute the installer in onw drive and install Symfony in another) so this would complicate things a lot. Let's close it for now as "won't fix" and we'll revisit it in the future. Thanks.

**Comment by ggirtsou** [comment]
This feature would come very handy, :+1: I understand it's a lot of work though.

This solution works pretty well: https://github.com/symfony/symfony-installer/issues/192#issuecomment-153991644
