### ISSUE TITLE
Add a command which retrieves list of all versions

### ISSUE THREAD

**Issue by Pierstoval** [symfony/symfony-installer#82]
Hi everyone, 
 
I was thinking tonight about a new evolution : list all available versions of Symfony.
In fact, I have to make a new project for someone but the environment is symfony 2.3, and I cannot update to 2.4 or more, so I wanted to create a project with SF2.3, but I didn't know which was the latest 2.3 release. 
 
The goal is to create a `symfony versions` command, which allows the user to view all available versions.
If you run `symfony versions 2.3.*` you'll see all 2.3 releases, sorted ascending (to see the last version in the console), or another `symfony versions 2.3.* --last` to get only the last release matching the version.

What do you think of the idea of using the github API ( https://api.github.com/repos/symfony/symfony/tags ) to retrieve all possible versions ?
Actually, I don't know how it is possible to handle this... I also thought about having symfony installed as a simple git bare repo, bundled in the phar file, and trying to `git fetch --all && git tag -l` . 
 
Tell me if it sounds good or not, I might work on this if we find a good solution to retrieve the tags :smile:

**Comment by javiereguiluz** [comment]
Closing this issue because we're working on this feature in other pull requests and issues.

**Comment by Pierstoval** [comment]
Thanks @javiereguiluz , may I add that it's more that we don't need this feature, as it is not really useful to the installer, and more because of issue #42 and PR #90 :smile:
