### ISSUE TITLE
Support 3.x directory structure for 2.5.x+ versions

### ISSUE THREAD

**Issue by tobymackenzie** [symfony/symfony-installer#93]
Installing with composer, you can get the 3.x directory structure by setting an environment variable of `SENSIOLABS_ENABLE_NEW_DIRECTORY_STRUCTURE` to true and then answering a question with 'y'.  It would be nice if an option was added to the `new` command to do the same thing.  I assume this would just involve making them available on 'http://symfony.com/download' (if they aren't already) and then having the `download()` method change the `$baseName` if the option is passed.

**Comment by javiereguiluz** [comment]
Closing it because we think adding this change it's not worth it. We prefer to keep staying on the safe side: use Sf2 dir structure for Sf2 apps and, when it's released, we'll use Sf3 dir structure for Sf3 apps.

We consider using Sf3 dir structure in Sf2 applications an edge case.
