### ISSUE TITLE
Add ability to choose config format

### ISSUE THREAD

**Issue by unkind** [symfony/symfony-installer#94]
I prefer to use XML as config format in Symfony projects because of autocomplete, instant validation, etc. It would be great to have ability to choose preferable format of configs in `app/config/*` (excepting `parameters.yml`).
User have to do manually it by himself for now.

**Comment by stof** [comment]
This would force us to create different flavors of the standard edition, so I'm not sure it is worth doing it now, especially given the best practices are telling to use YAML.
Advanced users can choose to switch to XML, but exposing this switch in the installer would also make it harder for beginners by making them understand this choice before they even start looking at a symfony project.

What do you think @javiereguilez and @weaverryan ?

**Comment by fabpot** [comment]
I'm strongly against providing choices here. The Standard Edition is the only place where we actually make choices for the user.

**Comment by javiereguiluz** [comment]
@stof I agree with Fabien. Moreover, in my opinion the Symfony Installer should be as much "feature-free" as possible and we could even declare it "finished" soon.

@unkind in any case, I think your concern is valid and preferring XML is perfectly fine. Fortunately, the Symfony application created with the installer contains almost no config files. It's true that `app/config/services.yml` is created, but it's almost empty. And it's true that `app/config/routing.yml` loads route via annotations, but it's a matter of deleting 3 configuration lines. All in all, in my opinion the current installer is *"convenient for people following best practices and almost neutral for people not following them"*.

Considering the strong opposition expressed by deciders, let's close this issue.
