### ISSUE TITLE
Allow to create project in current (Existing) directory just like Django does

### ISSUE THREAD

**Issue by felipsmartins** [symfony/symfony-installer#98]
Currently, Symfony installer version 0.5.0 not allow to create project in a current directory.
It would be nice this feature, just like [django-admin](https://docs.djangoproject.com/en/1.7/ref/django-admin/#startproject-projectname-destination) (from Django framwork) [does](https://docs.djangoproject.com/en/1.7/ref/django-admin/#startproject-projectname-destination):
```
~$ django-admin.py startproject  <projectname> [destination]
```
Where destination is a optional path to install in.  Using ‘.’ denotes the current working directory.
It would be:
```
~$ symfony new  <projectname> [destination] [version]
```
It would be too useful, for instance, when creating project from openshift where repository directory is created first.

**Comment by Pierstoval** [comment]
I think your proposal is quite good.
 
It then would need to change the actual behavior of the `new` command and make a difference between the project name and the destination, which will by default be the same as the project name, it may sound good then.

**Comment by javiereguiluz** [comment]
@felipsmartins you can already create the project in any directory, not only in the actual directory where you execute the installer:

```
$ symfony new my_project
$ symfony new /Users/javier/projects/my_project
```

The first command will create the project in the same directory as you are, but the second command will always create the project in the given directory.

**Comment by Pierstoval** [comment]
@javiereguiluz I think what @felipsmartins want is more a command to create project like this:

```shell
$ symfony new ./ 2.6
```
Which is impossible now. In fact, you must specify a "named" directory in order to create a new app. 
In technical terms, developing this kind of feature would need to set a default "project name" , because the actual project name is defined with the directory.

**Comment by javiereguiluz** [comment]
@Pierstoval I understand the problem now. We don't want to add any option to the installer, so what we could do is to check if the directory is actually empty. In that case, we would "overwrite" it because it's safe to do it. Is there any simple PHP function to know if a directory is completely empty of contents?

**Comment by Pierstoval** [comment]
`glob(*);` ?

**Comment by felipsmartins** [comment]
@Pierstoval Yes, you are right!
@javiereguiluz Would be nice! 
But I think that  symfony installer could to do somewhat like:
```
if (is_dir($destination)) {
    if (count(glob("$destination/*"))) {
        echo sprintf('%s is a non empty directory, you sure about to install in?', $destination);
    } else {
        //cancel
    }
}
```
Thus, I can to install symfony inside existing repo, for instance. Okay, thats seems like insane but happens!
It give us better flexibility.


Thanks!

**Comment by javiereguiluz** [comment]
This has been fixed in #99. I've used the code proposed by @Pierstoval.

@felipsmartins sadly, your proposal about installing Symfony even when the project is not empty couldn't be implemented. This behavior doesn't follow the usual Symfony practices of doing things and, in my opinion, it's extremely dangerous.

**Comment by ahurt2000** [comment]
However, with all due respect, I think that we should not let the installer run out of options for this case.
A project need not start with the installation of the framework, making it possible want to install this in a non-empty folder, for example folder containing .git, docs, etc. Sure you can always install it in another folder, but -
Why not give an option like "--force" or something like that ?. Leaving in the user choose if desired or not overwrite files and folders.

**Comment by aaronmu** [comment]
Agree with @ahurt2000 that a project doesn't always start with the installation of a framework.

@javiereguiluz why do you consider this "extremely dangerous"? How does it conflict with "the usual Symfony" practices?

**Comment by Pierstoval** [comment]
@aaronmu The reason I see is that using a `--force` option or similar behavior might induce overwriting files you might not want to overwrite. And implementing a "safety" behavior by proposing to overwrite current/all/no files is cumbersome (even if it's feasible).

**Comment by javiereguiluz** [comment]
@aaronmu if we add this option and you execute this:

```
$ symfony new /Users/myname/projects --force
```

The Symfony Installer will delete all the files of all your projects. We won't add this option because most of the people don't need it and because it opens the door to catastrophic consequences.

**Comment by kariae** [comment]
@javiereguiluz can the --force only creates the necessary files without deleting the old ones ?
A case where this will be helpful is if your development environment is based on Docker, so in general you'll already your app directory containing some files like Dockerfile ...

**Comment by Pierstoval** [comment]
> @javiereguiluz can the --force only creates the necessary files without deleting the old ones ?

The problem with that is that you can still do `symfony new /usr/ --force` (or worse, `symfony new / --force`) and create files in **really** not wanted places.

For docker, then you just do `symfony new sf_app && mv sf_app/* ./` (and don't forget to copy hidden/dot files not touched by `mv`)

**Comment by kariae** [comment]
> The problem with that is that you can still do symfony new /usr/ --force (or worse, symfony new / --force) and create files in really not wanted places.
I think that the user can be aware of that, and since the old files (of the application folder) will not be erased, as you said, the worst case he will have Symfony files in his folder.
The solution you proposed for Docker will work, it's actually the one I use today, but it's a little bit twisted.

**Comment by Pierstoval** [comment]
> The solution you proposed for Docker will work, it's actually the one I use today, but it's a little bit twisted.

Twisted maybe, but still the most secure way

**Comment by MPLLC** [comment]
Can #99 be modified to allow for hidden directories, like .git?

**Comment by Pierstoval** [comment]
@MPLLC I think it's a good idea 😄 Want to make a PR? 😉
